### ISSUE TITLE
Program Exit

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#1]
When '_Close to System Tray_' is enabled in '_Options_' then '_Exit_' command does not work neither from '_File_' nor from '_Tray_' , screen:

![http downloader 1 0 0 6 - 2018-09-13 - 002](https://user-images.githubusercontent.com/9025757/45513609-cbb92800-b7ab-11e8-8ad5-f7837fee449b.png)

'_Exit_' should work even when '_Close to System Tray_' is enabled, both from '_File_' and from '_Tray_'.

This happens with [HTTP Downloader](https://github.com/erickutcher/httpdownloader) version [1.0.0.6](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.0.6) (under Windows 8 x64).

**Comment by erickutcher** [comment]
Good catch. I'll have something released to fix this by this weekend. If not before.

**Comment by smaragdus** [comment]
@erickutcher 

I can confirm that the bug is fixed, thank you!
