### ISSUE TITLE
Exception hotkey

### ISSUE THREAD

**Issue by RatError** [erickutcher/httpdownloader#107]
Is it possible to add an exception hotkey to the extension?
For example, when you Click +Alt (or another), the link is not intercepted, but is processed in a standard way. There are sites where the download button does not lead to a link, but runs a script: torrent tracker, university website. There, when you click on download, a link is generated with the user’s ID and is loaded. The program downloads PHP, you have to disable the "Override" checkbox on these sites, then turn it on.
There is even free space in the extension window, you could  add an input field or a checkbox.
![HotKey](https://user-images.githubusercontent.com/58669239/72319438-389a4600-36b0-11ea-98ee-555ef823e9cd.png)

**Comment by erickutcher** [comment]
New version is up.
