### ISSUE TITLE
Global Download Speed Limit Window Value

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#108]
Please consider improving the **Global Download Speed Limit Window** to show a value textbox (to the left) and a drop-down box (to the right).

_The selections could be:_
_- KB/s_
_- MB/s_

That way it's more human friendly 😸

**Comment by erickutcher** [comment]
I considered a drop-down menu, but liked the ability to fine tune the value without any extra clicks. If you hover over the textbox, it'll show a tooltip that gives you the formatted value.

**Comment by hl2guide** [comment]
Okay 👍 , is it possible to decrease the delay for showing the  tooltip?

**Comment by erickutcher** [comment]
As long as you have the mouse hovered over the textbox and a tooltip is showing, then anything you type in it will update the tooltip immediately.

**Comment by hl2guide** [comment]
For me it's a delay of 1 second each time it's changed.

**Comment by erickutcher** [comment]
This is what it should look like:

![FQyvQxpuqW](https://user-images.githubusercontent.com/7762164/73597793-e8f7af00-44e4-11ea-87fc-c4bff1115854.gif)

Behaves the same on Windows 7 too. The delays are determined by Windows' double click speed. Maybe you have a setting on your system somewhere that's too high or too low?
