### ISSUE TITLE
Server Authentication seems to fail

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#109]
Server Authentication seems to fail for downloads.

Firefox Extension Settings:
![1](https://user-images.githubusercontent.com/17044982/72672089-3b7aa980-3aa9-11ea-8ed9-cc6e9156602c.png)

App Settings:
![2](https://user-images.githubusercontent.com/17044982/72672090-3b7aa980-3aa9-11ea-8748-a19fac023913.PNG)

Result:
![3](https://user-images.githubusercontent.com/17044982/72672091-3c134000-3aa9-11ea-94d1-a34b923fd103.PNG)

**Comment by erickutcher** [comment]
Check that your passwords match. If they do, then try using a different port.

**Comment by hl2guide** [comment]
What I've checked:
- Passwords do match
- port 8099 fails
-port 8080 fails
- digest authentication tried

I've given up trying it out :(

**Comment by erickutcher** [comment]
Did it work in previous versions? Does it work without authentication?

**Comment by erickutcher** [comment]
Also make sure you're using the latest version of the program and extension.

**Comment by hl2guide** [comment]
Latest version of both, it works without authentication.

I never got it working in the past (previous versions).
