### ISSUE TITLE
Export History

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#11]
I would like to suggest a new feature:

- **Export History**

perhaps accessible via 'File' - 'Export History' which would allow the user to save download history to file (**TXT** file, **HTML** file, or both). I suppose that such a feature would be useful (at least for me it would be).

**Comment by erickutcher** [comment]
I have code in other programs that exports to CSV. This shouldn't be a problem to implement. A CSV file is a little more versatile than TXT and HTML. At least when it comes to displaying grid data.

**Comment by erickutcher** [comment]
The history can now be saved as a CSV file, or exported and imported as a download_history file. These are accessed from the File menu.

**Comment by smaragdus** [comment]
I tested both export and import and both worked fine, thanks. Yet I think that txt or html is easier for viewing but csv is fine too.
