### ISSUE TITLE
Progress Bars Colours

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#110]
I updated from version [1.0.2.9](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.2.9) to version [1.0.3.0](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.3.0) without changing any settings in program options yet the progress bar colours are different:

- Progress Bars - HTTP Downloader version 1.0.2.9
  - progress bar in task bar - green
  - progress bar in system tray - green
  - progress bar in URL drop window - green

- Progress Bars - HTTP Downloader version 1.0.3.0
  - progress bar in task bar - green
  - progress bar in system tray - violet
  - progress bar in URL drop window - violet

Screens:

HTTP Downloader 1.0.2.9 - progress bar in task bar:

![HTTP Downloader 1 0 2 9 - 2020-01-19 - 001](https://user-images.githubusercontent.com/9025757/72673424-fb003900-3a72-11ea-88a9-84d0b2785bb1.png)

HTTP Downloader 1.0.2.9 - progress bar in system tray:

![HTTP Downloader 1 0 2 9 - 2020-01-19 - 002](https://user-images.githubusercontent.com/9025757/72673436-1f5c1580-3a73-11ea-8fdd-0ab19ea741d7.png)

HTTP Downloader 1.0.2.9 - progress bar in URL drop window:

![HTTP Downloader 1 0 2 9 - 2020-01-19 - 003](https://user-images.githubusercontent.com/9025757/72673446-4581b580-3a73-11ea-83be-920cffd590c1.png)

HTTP Downloader 1.0.3.0 - progress bar in task bar:

![HTTP Downloader 1 0 3 0 - 2020-01-19 - 001](https://user-images.githubusercontent.com/9025757/72673460-8a0d5100-3a73-11ea-9c1f-6975de753e40.png)

HTTP Downloader 1.0.3.0 - progress bar in system tray:

![HTTP Downloader 1 0 3 0 - 2020-01-19 - 002](https://user-images.githubusercontent.com/9025757/72673462-95607c80-3a73-11ea-8928-079a9d59bc71.png)

HTTP Downloader 1.0.3.0 - progress bar in URL drop window:

![HTTP Downloader 1 0 3 0 - 2020-01-19 - 003](https://user-images.githubusercontent.com/9025757/72673467-9db8b780-3a73-11ea-9685-0d14fcbcffb8.png)

Is this change intentional? Or the problem is in my system? I prefer unified progress bar colours.

**Comment by erickutcher** [comment]
Yes this is intentional. The colors can be changed in the Appearance options. The Progress Color and Border Color for Downloading, Paused, and Failed downloads are used for the tray icon and URL drop window.

I see your point about making them consistent with the OS. I overlooked that. Perhaps I'll make them separate color options in the next version. And I'll have their defaults set to match the system's.

**Comment by smaragdus** [comment]
@erickutcher 

Perhaps I did not explain well enough what I meant. What I was wondering was why the progress bar for downloading was green in task bar and violet in system tray and in URL drop window. The status is one and the same- downloading, yet the colours are 2- green for task bar, violet for system tray and in URL drop window. I think it should be either green or violet. Perhaps I am missing something?

**Comment by erickutcher** [comment]
The taskbar colors can only be green, yellow, or red. Windows dictates that. The tray icon and URL drop window progress colors can be anything. In prior versions I had the colors set to the same values that Windows uses. In the latest version the colors match the values that are used in the main window.

I've added some settings to the Appearance options that'll allow you to set the tray icon and URL drop window progress colors separately from the main window progress colors. By default, the values will be the same as what Windows uses.

![options](https://user-images.githubusercontent.com/7762164/72675403-2b76b180-3a38-11ea-8aec-827ad1a652ba.png)

**Comment by smaragdus** [comment]
@erickutcher 

> The taskbar colors can only be green, yellow, or red. Windows dictates that.

Actually I was not aware of that. If I were I would not have opened this issue. I would have preferred violet everywhere but unfortunately it is not possible for the progress bar in task bar.

> I've added some settings to the Appearance options that'll allow you to set the tray icon and URL drop window progress colors separately from the main window progress colors. By default, the values will be the same as what Windows uses.

I rarely see the progress bar in task bar because HTTP Downloader usually stays hidden in system tray, If I knew that Windows did not allow other colours than green, yellow or red I would not have opened this issue. I am really sorry that I burdened you with unnecessary work- I did not not pay enough attention to the [change log](https://github.com/erickutcher/httpdownloader/blob/master/HTTP_Downloader/changelog.txt). As I know now that the progress bar in task bar cannot match the values used in the main window I would keep progress bar settings as they are. I am sorry if I wasted a lot of your time.

**Comment by erickutcher** [comment]
It wasn't a waste. I actually prefer that the colors are separated from the main window. It's a little more flexible now.

**Comment by erickutcher** [comment]
The new version has 6 settings that affect the progress bar colors for the system tray icon and URL drop window. By default, they match the taskbar progress colors (green, yellow, and red).

**Comment by smaragdus** [comment]
@erickutcher 

When I try to use 'Add to Custom Colors' command for 'Progress Color' the colour is not saved permanently in 'Custom colors'.

The procedure I tried:

- Go to Options
- Go to Appearance
- Go to Progress bar:
- Go to Downloading
- Go to Progress Color
- Hit Add to Custom Colors command
- Hit OK
- Hit Apply
- The colour is not saved in Custom colors

Can you confirm this?

**Comment by erickutcher** [comment]
Yeah, I never bothered dealing with that parameter for the color picker. It's easy enough to implement.

I'll have it done for the next release. It'll take some time though because I'm overhauling the Login Manager. I'm turning it into a Site Manager that'll allow per site settings.
