### ISSUE TITLE
Extension Icon

### ISSUE THREAD

**Issue by RatError** [erickutcher/httpdownloader#112]
Thanks for adding useful features, especially the file rename function and the override disable hotkey.
As a wish - is it possible to make different icons for different extension states?
For example, the standard, blue icon - overrides on, and monochrome - overrides off.
Now, sometimes you can’t figure out what state the extension is in now.
P.S. The problem of a transparent window was solved by enabling compatibility with W8))

![Ex Icon On](https://user-images.githubusercontent.com/58669239/72690167-9accce00-3b2a-11ea-8956-640fa7c22ce4.jpg) ![Ex Icon Off](https://user-images.githubusercontent.com/58669239/72690171-a6b89000-3b2a-11ea-91d8-6a48b3860324.jpg)

**Comment by erickutcher** [comment]
The icon color change is doable.

I didn't think about changing the program's compatibility mode. The fact that it works definitely points to an early Windows 10 issue. Glad it's working though.

**Comment by erickutcher** [comment]
I've released some new extensions that change the icon color when overriding the browser's download manager. When it's not overridden, it'll use the light blue icon. When it is overridden, it'll be a light green icon.
