### ISSUE TITLE
Actions for "Add using Defaults" and "Download using Defaults" Functions

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#115]
Please consider adding a "Add using Defaults" and a "Download using Defaults" to the main context menu. It'd be quite useful 👍 

Currently:
![example](https://user-images.githubusercontent.com/17044982/73514961-b481e580-4447-11ea-9186-02a52f7c4915.png)

For these the function would be to add/download a URL using the default folder with no "Add URL(s).." dialog shown or extra options to select. It just appears on the list.

Supporting one or more URLs that are copied into the **Windows Clipboard**. (multi-line)

Basic Pseudocode for Context Menu:
`
IF (WINDOWS_CLIPBOARD CONTAINS ONE OR MORE URLS)
THEN
ENABLE BOTH MENU ITEMS
ELSE
DISABLE BOTH MENU ITEMS
`

**Comment by erickutcher** [comment]
I think the context menu would be too cluttered with more items.

In the Advanced Options there's a drop-down menu to allow you to download or add drag and drop URL(s) immediately instead of opening the Add URL(s) window. It'll use the default values that are set in the Options.
