### ISSUE TITLE
Auto copy URLs in Windows Clipboard into Add URL(s)' dialog

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#116]
Please consider adding a checkbox option for:
Automatically copy URLs from Windows Clipboard into the 'Add URL(s)' dialog.

It'd help speed up the process of adding items.

**Comment by erickutcher** [comment]
This should already be the case. If there's a URL on the clipboard, and you open the Add URL(s) window, then it'll paste it in the URL(s) textbox.
