### ISSUE TITLE
Fix for Export/Import Download History

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#117]
Currently the **Export/Import Download History** feature results in a file with no file extension.

![1](https://user-images.githubusercontent.com/17044982/73524224-cae86b00-4460-11ea-97a4-69c99cfd9eaa.PNG)

Please also consider a **default filename** for the File Selector dialog, currently blank.

**Comment by smaragdus** [comment]
@hl2guide 

Why do you need a file extension for `download_history` file? It can be read only by [HTTP Downloader](https://erickutcher.github.io/#HTTP_Downloader).

**Comment by hl2guide** [comment]
hmm, just seems old to me, Windows shows it as a blank icon.

If the file is just XML maybe the .xml extension would be good?

**Comment by erickutcher** [comment]
All the files that get generated are binary files. I could give it a .hdh extension and allow them to import if they're clicked. I'm not going to modify the registry to have Windows associate the file type though.

**Comment by erickutcher** [comment]
A new version is up. If you save a download history file now, it'll have the .hdh extension. You'll want to have Windows associate that extension with HTTP Downloader in order for the program to load it on click.
