### ISSUE TITLE
Clear History

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#12]
Currently (as of version [1.0.0.7](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.0.7)) the download history can be cleared via 'CTRL+A' command and 'Remove Selected' context menu command. 

You may add an option to use 'Del' command to delete selected download(s). Thus the user would not need to use 'Remove Selected' command via context menu- just mark a download and then press 'Del' key. This would be equal to 'Remove Selected' context menu command and it would be handy for those accustomed to use the keyboard- 'CTRL+A' selects all downloads, 'Del' deletes all downloads. For me the combination of 'CTRL+A' to select all and 'Del' to delete selected is logical and its usage is common.

You may also add a new context menu command- 'Remove All' (perhaps below 'Remove Selected' command) which clears all download history.

**Comment by erickutcher** [comment]
Here's some shortcut keys that I have implemented.

Ctrl + A = Select all
Ctrl + D = Delete selected item(s).
Ctrl + R = Rename selected item (one item at a time).
Del = Remove selected item(s).

**Comment by smaragdus** [comment]
Thanks for the shortcuts. Perhaps you may add also a shortcut for 'Add URL(s)' dialog? Perhaps 'CTRL+N'?

**Comment by erickutcher** [comment]
I'll do that for a future release. And also add one for the Options window.

**Comment by smaragdus** [comment]
> Here's some shortcut keys that I have implemented.
> 
> Ctrl + A = Select all
> Ctrl + D = Delete selected item(s).
> Ctrl + R = Rename selected item (one item at a time).
> Del = Remove selected item(s).

For me:

- `Ctrl + A` works fine;
- `Ctrl + D` does not work at all;
- `Ctrl + R` does not offer to rename the selected item but triggers `Are you sure you want to remove the selected entries?` dialog;
- `Del` works fine;

This happens with version [1.0.1.0](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.1.0). Will you please confirm?

**Comment by erickutcher** [comment]
The new shortcuts for those commands are listed in the Edit menu.

Here's all of the shortcuts:

F2 = Rename
Del = Delete
Ctrl + R = Remove
Ctrl + Del = Remove and Delete
Ctrl + C = Copy URL(s)
Ctrl + A = Select All

Ctrl + N = opens Add URL(s) window

Ctrl + S = opens Search window
Ctrl + O = opens Options window

**Comment by smaragdus** [comment]
Thanks for the list of shortcuts, somehow I missed to check 'Edit' menu.
