### ISSUE TITLE
HTTPS Only Setting

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#121]
Please consider adding a setting (Checkbox) for ignoring all HTTP links, and only allowing/adding HTTPS links (secure connection).

**Comment by erickutcher** [comment]
I would use a RegEx filter for this: `^https:\/\/.*`

**Comment by smaragdus** [comment]
I do not see what is the point to block HTTP downloads, this would cripple the program and the downloads. This obsession with HTTPS is beyond common sense.
