### ISSUE TITLE
Download Stopped

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#126]
When I try to download from this [site](https://release.tinymediamanager.org/) the download fails to start- it appears as 'Stopped' in 'Progress' column, screen:

![HTTP Downloader 1 0 3 1 - 2020-03-01 - 001](https://user-images.githubusercontent.com/9025757/75618888-01f38e80-5b7d-11ea-9f81-993ce2e8af3f.png)

Another download manager - [Free Download Manager](https://www.freedownloadmanager.org/), also failed to download from this site showing 'Unknown network error', screen:

![Free Download Manager 3 9 7 Build 1627 - 2020-03-01 - 001](https://user-images.githubusercontent.com/9025757/75618964-fd7ba580-5b7d-11ea-94aa-6419f3ce4015.png)

- [example download link 1](https://release.tinymediamanager.org/v3/dist/tmm_3.1.3_win.zip)
- [example download link 2](https://release.tinymediamanager.org/v2/dist/tmm_2.9.17.1_bf18047_win.zip)

However the download completed just fine when downloaded via browser.

I wonder what causes these downloads to be stopped and whether the problem is on my end.

**Comment by erickutcher** [comment]
Both links work fine for me. I'd say it's a network issue, but you said your browser is able to download it. Maybe it's a DNS issue?

**Comment by smaragdus** [comment]
@erickutcher 

Thanks for the test,  As the downloads work for you I will close this issue. Obviously the problem is on my end. I do not know what is causing the problem as all other downloads work just fine.

**Comment by smaragdus** [comment]
@erickutcher 

I had another instance of 'Download Stopped' problem, it appeared both with version [1.0.3.1](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.3.1) and the latest version [1.0.4.1](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.4.1), screen:

![HTTP Downloader 1 0 4 1 - 2021-05-11 - stopped -  001](https://user-images.githubusercontent.com/9025757/117882128-af4e5000-b2b2-11eb-997b-d4f227aaf3af.png)

The links that caused this problem:

- [Link 1](https://www.northglide.com/SideSlide_v4.80_Setup.zip) (**SideSlide_v4.80_Setup.zip**)
- [Link 1](https://www.northglide.com/SideSlide_v4.80_Portable.zip) (**SideSlide_v4.80_Portable.zip**)
- [Website](https://www.northglide.com/sideslide_download.html) (**SideSlide**)

[Free Download Manager](https://www.freedownloadmanager.org/) and [uGet](https://sourceforge.net/projects/urlget/) also failed to fetch the files, while [Ant Download Manager](https://antdownloadmanager.com/) managed to get these files, screen:

![Ant Download Manager 2 2 4 Build 77918 - 2021-05-11 - 001](https://user-images.githubusercontent.com/9025757/117881634-23d4bf00-b2b2-11eb-9a99-e3c32e17d6a1.png)

The browser was also able to download these files.

However when I changed the download links from HTTPS to HTTP:

`https://www.northglide.com/SideSlide_v4.80_Setup.zip -> http://www.northglide.com/SideSlide_v4.80_Setup.zip`
`https://www.northglide.com/SideSlide_v4.80_Portable.zip -> http://www.northglide.com/SideSlide_v4.80_Portable.zip`

the downloads were completed successfully, screen:

![HTTP Downloader 1 0 4 1 - 2021-05-11 - stopped -  002](https://user-images.githubusercontent.com/9025757/117882223-c8ef9780-b2b2-11eb-996a-5b342aa16177.png)

I wonder whether this problem is reproducible or it occurs on my machine only.

Regards

**Comment by erickutcher** [comment]
The HTTPS links work perfectly fine for me. I'm on Windows 10 right now. It's hard to say what's going on. Ant Download Manager could be falling back to HTTP if HTTPS fails. I don't think Firefox or Chrome use the Windows TLS API. Are you able to download the HTTPS links with Internet Explorer?

**Comment by smaragdus** [comment]
@erickutcher 

Thanks for checking these links.

Internet Explorer failed to download these HTTPS links, screen:

![Internet Explorer - 2021-05-13 - SideSlide - 002](https://user-images.githubusercontent.com/9025757/118172418-0419d400-b435-11eb-94d2-362ea60e850f.png)

Although All SSL and TLS versions are enabled, screen:

![Internet Explorer - 2021-05-13 - SideSlide - 003](https://user-images.githubusercontent.com/9025757/118172592-3a575380-b435-11eb-977e-b6453370377f.png)

It seems that this problem is system related (on Windows 8).  By the way I recently changed my ISP.

As you confirm that the problem is unrelated to HTTP Downloader no further investigation is needed,

Regards
