### ISSUE TITLE
Remove Selected

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#13]
When 'Remove Selected' command is executed for incomplete download the partially downloaded file is not removed from disk. What about an option to also remove incomplete downloads from disk? I suppose that if the download is unfinished 'Remove Selected' command should remove the partially downloaded file or there might be another context menu command:

- **Delete File from Disk**

which deletes the (partially) downloaded file from disk if it hasn't been already deleted manually.

**Comment by erickutcher** [comment]
I ended up renaming the "Remove Selected" menu item to "Remove" and added a "Delete" menu item as well. Remove will remove it from the list only. Delete will delete it from the disk only.

I also implemented a "Rename" menu item that will let you rename the file after it's been added and is created on the disk. One of the Portable Freeware members mentioned something about being able to rename the downloads.

A full list of changes is here: https://github.com/erickutcher/httpdownloader/commit/fffc02abe2f2b1950a46a6438d527a2f88a12ced

One thing I forgot to list in the change log is that I changed the download_history file slightly. So the old history won't load in this newer version.

**Comment by smaragdus** [comment]
The 'Rename' context menu item is fine. You may also bind 'Rename' to 'F2' key which seems a logical shortcut to me.
'Remove' and 'Delete' are fine. What about 'Cancel' which removes the download from list and deletes the file from disk? In short- 'Cancel' is working as 'Remove' and 'Delete' combined. In my opinion 'Cancel' may be useful for incomplete downloads.

**Comment by smaragdus** [comment]
I can think of a couple possible solutions:

 either _cascading context menu_:

- **Delete**
  - **Link**
  - **File**
  - **Link & File**

or _normal context menu_:

- **Delete Link**
- **Delete File**
- **Delete Link & File**

Perhaps _normal context menu_ would not look that good (longer commands) but would be faster (1 click in stead of 2 clicks).

Perhaps if you choose only **Delete** (no matter 3 sub-menus to main command or 3 separate commands) it would be less ambiguous than using **Remove**, **Delete**, **Cancel** commands together.

**Comment by erickutcher** [comment]
I ended up doing Remove, Remove And Delete, Delete. The menu still flows nicely.

**Comment by smaragdus** [comment]
> I ended up doing Remove, Remove And Delete, Delete. The menu still flows nicely.

This sounds logical.

**Comment by smaragdus** [comment]
The current context menu commands- `Remove`, `Remove and Delete` and `Delete` are clear and convenient. The current order is:

- Remove
- Remove and Delete
- Separator
- Rename
- Delete

I think that the following order would be more logical:

- Remove
- Remove and Delete
- Delete
- Separator
- Rename

What do you think?

**Comment by erickutcher** [comment]
I should probably swap Rename and Delete so that it's consistent with Explorer, but I want to keep the separator in place. It sort of isolates items that affect the program and items that affect the system.
