### ISSUE TITLE
feature request: add option-dialog Save As in Add URL dialog box

### ISSUE THREAD

**Issue by Viteczech** [erickutcher/httpdownloader#133]
add option-dialog Save As with to (re)name the downloaded file in the Add URL dialog box

**Comment by erickutcher** [comment]
To set a filename in the Add URL(s) window you'll want to put the filename in brackets before the URL. For example:

```
[webpage.html]http://www.example.com/file.html
[foobar.mp3]http://www.example.com/music.mp3
```

I did it this way because a Save As... dialog wouldn't really work for multiple files.

**Comment by Viteczech** [comment]
Thanks, also solutions.
