### ISSUE TITLE
Running from a .bat

### ISSUE THREAD

**Issue by jabm2000** [erickutcher/httpdownloader#134]
When executing it from a .bat file with its parameters, the program remains open. Is there a parameter for the .bat that closes the program after the transfer is complete?
Thank you.
P.D.: great program.

**Comment by erickutcher** [comment]
I don't think there's a way to alert the bat file unless it monitors the download history file's last modified date. That gets saved after all active downloads finish. I could implement a setting that shuts the program down after all transfers have been completed.

**Comment by jabm2000** [comment]
Thanks for your attention.
It could be passing a parameter with (--) like, e.g. (--ulr .....), or maybe put a tick in Tools -> Options ....
Thank you very much for your interest.

**Comment by erickutcher** [comment]
I'll make a setting in the advanced options and a command-line switch. It'll be some time before I do a release of these features. I'm still working on these features first: https://github.com/erickutcher/httpdownloader/issues/59

Also, my monitor died today so I have to wait for a replacement to arrive before I get back to things. It was 11 years old so I shouldn't be surprised.

**Comment by erickutcher** [comment]
Here's a beta version that implements the exit after complete feature: https://github.com/erickutcher/httpdownloader/issues/59#issuecomment-650648907
