### ISSUE TITLE
Add URL(s) does not paint completely with download in progress

### ISSUE THREAD

**Issue by JNavas2** [erickutcher/httpdownloader#135]
ENVIRONMENT:
Windows 8.1 Pro x64 with High DPI display
HTTP Downloader 1.0.3.1 (64-bit)
TO REPRODUCE:
1. Open Add URL(s) and start a download.
2. Open Add URL(s) a 2nd time.

WHAT SHOULD HAPPEN:
Same Add URL(s) window.
WHAT DOES HAPPEN:
_Transparent non-functional_ Add URL(s) window.
WORKAROUND:
Minimize or maximize Add URL(s) window, then restore it, makes it work properly.
COMMENT:
Thank you for HTTP Downloader!

<img width="450" alt="Capture" src="https://user-images.githubusercontent.com/14850792/81509327-9a656800-92be-11ea-8de8-b6c884ebb084.PNG">

**Comment by erickutcher** [comment]
That's a bug in Windows sadly. Early versions of Windows 10 and I'm guessing the latest 8.1 have issues with the creation of a window that uses the WS_EX_COMPOSITED flag. I use that to prevent the window from flickering when it gets resized.

I'll have to ignore that for Windows 8/8.1 systems.

**Comment by JNavas2** [comment]
Thank you.

**Comment by erickutcher** [comment]
Try this beta version out and see if it fixes the problem: https://github.com/erickutcher/httpdownloader/issues/59#issuecomment-650648907

**Comment by JNavas2** [comment]
With **[1.0.3.2 Beta 2 64-bit](https://www.youtube.com/watch?v=NUCtlBalBv4)**, the download does not appear in the window!
If I close and reopen the program, then it does appear.

But, with **[1.0.3.1 64-bit](https://youtu.be/D__GBKEsmzE)**, I can no longer reproduce the Add URL problem!
So you can **Close** this issue.

(Links are to YouTube videos.)

**Comment by erickutcher** [comment]
Thanks for the videos. I fixed the add download issue with this version: https://github.com/erickutcher/httpdownloader/files/4841640/HTTP_Downloader_1.0.3.2b2.zip

Since the download list is now a custom control there's still some bugs to work out. I've tried to make it look just like a standard listview control, but it'll have tree like capabilities as well when it's finished.
