### ISSUE TITLE
Version 1.0.3.3 --output-directory [path] not working

### ISSUE THREAD

**Issue by shimon128** [erickutcher/httpdownloader#141]
In the CMD is  ![image](https://user-images.githubusercontent.com/70193333/91132094-c3ff9f00-e6b5-11ea-8eb3-a15cbfeab15d.png)
But he download to somewhere else
![image](https://user-images.githubusercontent.com/70193333/91133654-33758e80-e6b6-11ea-94ed-0f746c340e81.png)

**Comment by shimon128** [comment]
I understand it has been fixed?
Is there anything new I need to download?

**Comment by erickutcher** [comment]
I'll be releasing a new version by the end of the week that contains the fix.

**Comment by shimon128** [comment]
Thanks

**Comment by erickutcher** [comment]
A new version is up.

**Comment by shimon128** [comment]
The problem still exists as you can see.
![image](https://user-images.githubusercontent.com/70193333/91652759-e7a25b00-eaa2-11ea-9b0c-433c6e24b21b.png)
![image](https://user-images.githubusercontent.com/70193333/91652768-f983fe00-eaa2-11ea-8ae2-352c62e7fbf1.png)
