### ISSUE TITLE
Version 1.0.3.4 --output-directory [path] not working

### ISSUE THREAD

**Issue by shimon128** [erickutcher/httpdownloader#143]
The problem still exists as you can see.
![image](https://user-images.githubusercontent.com/70193333/91652759-e7a25b00-eaa2-11ea-9b0c-433c6e24b21b.png)
![image](https://user-images.githubusercontent.com/70193333/91652768-f983fe00-eaa2-11ea-8ae2-352c62e7fbf1.png)

**Comment by erickutcher** [comment]
This should definitely be fixed now. Some variables weren't being set when the immediate argument was used. I've released a new version.

**Comment by shimon128** [comment]
Definitely fixed.
Thanks.
