### ISSUE TITLE
Interception filter

### ISSUE THREAD

**Issue by anonymous1184** [erickutcher/httpdownloader#144]
Is there a way to filter (in browser extension)? Like, don't use for images and files smaller than X bytes.

**Comment by erickutcher** [comment]
Currently it's not possible to filter based on file size. When the extension is set to override the browser's download manager, it would be possible, in some cases, to detect the file size and allow it through. The same could be done with images (or whatever file type). In either case, it's probably better to manually check the size and file type. I'll think about it.

**Comment by anonymous1184** [comment]
Thanks a lot, will wait in for it in case you decide to implement it.
