### ISSUE TITLE
File IO Error for 1.0.3.6

### ISSUE THREAD

**Issue by rayman3003** [erickutcher/httpdownloader#147]
When downloading with the version 1.0.3.6 (x64) of HTTP Downloader (Portable), It shows "File IO Error" for **any** link.

Screenshot:

https://picspy.info/images/82391981922517948422.jpg

Settings:

[http_downloader_settings.zip](https://github.com/erickutcher/httpdownloader/files/5473607/http_downloader_settings.zip)

This error won't happen for previous versions (1.0.3.1)(Portable) with the same settings.

I tried running the HTTP Downloader 1.0.3.6, with admin's right, But it doesn't helped. Also I allowed Downloader 1.0.3.6 through firewall too.

**Comment by erickutcher** [comment]
Your default download directory in the Advanced options is set to: H:\Temp-H3\1

Does that path exist on the system? If not, then it'll cause the File IO Error.

**Comment by rayman3003** [comment]
> 
> 
> Your default download directory in the Advanced options is set to: H:\Temp-H3\1
> 
> Does that path exist on the system? If not, then it'll cause the File IO Error.

Oh, my bad. I accidentally delete it & forgot it. I create it again & now its work. (◦'ںˉ◦)
