### ISSUE TITLE
Windows XP support

### ISSUE THREAD

**Issue by c-sanchez** [erickutcher/httpdownloader#15]
Hi, with last release HTTP Downloader is not working in Windows XP, please fix this if not problem.

**Comment by c-sanchez** [comment]
Yes, version 1.0.0.7 runs smoothly
![Image](https://image.ibb.co/gfYrDp/httpdownloader0001xa.png)

All that's missing in _HTTP Downloader 1.0.0.8_ is '**SetFileInformationByHandle**' from '**KERNEL32.DLL**'
and maybe something I don't know what it is in '**IEFRAME.DLL**'
verified with _Dependency Walker_.

**Comment by erickutcher** [comment]
I've released a new version. Hopefully it fixes things.

**Comment by erickutcher** [comment]
Create a folder called "locale" and put it in the same folder as HTTP Downloader. Then place the "default" locale in the "locale" folder.

**Comment by c-sanchez** [comment]
I see, thanks @erickutcher , now all works :D

**Comment by smaragdus** [comment]
@erickutcher 

Another user has confirmed that versions [1.0.0.9](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.0.9) and [1.0.1.0](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.1.0) run just fine under _Windows XP_ ([post](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24325&p=91905#p91902)). I suppose that this issue can be closed now.

**Comment by erickutcher** [comment]
Excellent.
