### ISSUE TITLE
1.0.3.6 Bug - Initial drop window drag-and-drop ignores settings

### ISSUE THREAD

**Issue by FredThompsonII** [erickutcher/httpdownloader#150]
If you have the option for "Drag and drop URL(s) action:" set to "Add in Stopped state", the first time you drag-and-drop onto the URL drop window you will be presented with options and that setting is shows as "Download."

After that, the URL drop window acts as a drop, not a drop-and-set-options.

Please fix this.

**Comment by erickutcher** [comment]
Thanks for the bug report. It'll be fixed in the next release.

**Comment by erickutcher** [comment]
A new release is up and this should be fixed.

**Comment by FredThompsonII** [comment]
Drag-and-drop on the drop window works properly if the setting is to download, true.
If the setting is "Add in stopped state", the item(s) dropped are downloaded, not added to the list.
Personally, I will frequently drag long lists of items then remove the ones I don't want from the list. A good example would be a cross-platform build of something here on GitHub which might have 30 files. I'm only interested in Linux, Mac, and Windows files, not other stuff like checksums, iOS builds, etc.

Please look at at this again, thanks.

**Comment by erickutcher** [comment]
It seems some changes I made after I fixed it caused the bug to pop up again. I've released a new version that should definitely have fixed it this time.
