### ISSUE TITLE
Restarting download results in skipped status

### ISSUE THREAD

**Issue by char101** [erickutcher/httpdownloader#152]
Hi,

If I configure the application to skip downloading an already downloaded file, restarting a download results in the download item status becoming **Skipped**. In my opinion, asking to restart a download mean that I intentionally want the existing file (if any) to be overwritten. In this case the server where I downloaded the file send a 404 status page instead of the file content (maybe with a `200` status code since the download status is **Completed**).

**Comment by erickutcher** [comment]
I can make it so that it displays the rename/overwrite/skip prompt when restarting.

**Comment by char101** [comment]
I guess a prompt could be useful when someone accidentally click on the restart context menu item.

What's weird is that if I restart a completed download, it failed with skipped status. If I restart it again (the item with skipped status), it works (i.e. the existing file is overwritten).

**Comment by erickutcher** [comment]
> What's weird is that if I restart a completed download, it failed with skipped status. If I restart it again (the item with skipped status), it works (i.e. the existing file is overwritten).

You may need to send me your settings file and an example URL in which this happens.

**Comment by char101** [comment]
I changed the option value to _Display Prompt_ and selected overwrite + remember settings and now it can overwrite the existing file when the download is restarted, so I guess that solve the problem for me.

**Comment by erickutcher** [comment]
I reworked a lot of the code that deals with starting/restarting downloads so hopefully when I release the new version it'll work how you'd expect it to.
