### ISSUE TITLE
Message dialog always shown in the first monitor

### ISSUE THREAD

**Issue by char101** [erickutcher/httpdownloader#155]
Hi,

I think there is a regression with the new message dialog change where it now always appears in the first monitor only although httpdownloader window is being put in the second monitor.

Thanks.

**Comment by erickutcher** [comment]
Since I don't have a multi-monitor setup, I never would have known this. I'll see what I can come up with.

**Comment by erickutcher** [comment]
I tested things out with my laptop hooked up to my TV. It was set to use the TV as an extended display. When I dragged the program to the second desktop and ran it, it opened up on the first desktop. I then dragged the running program over to the second desktop and opened up some windows (Add URL(s), Options, About, etc.). All of those windows opened up on the first desktop while the main window was on the second desktop. Is that basically what you're experiencing?

I found some code to deal with it and I'll work on in this weekend.

**Comment by char101** [comment]
Yes, that is what happened. In the previous versions, dialog boxes opened in the same monitor. Thanks.

**Comment by erickutcher** [comment]
A new version is up.

The main window will open up on whatever monitor it's run from. All child windows will open up in whatever monitor the main window is on. The exception to that is the Add URL(s) and Search windows. Those will initially open up wherever the main window is, but if they're opened up again, then it'll be from their last position regardless of where the main window is. The main window and URL drop window will remember their positions when starting up as long as they're started in the same monitor as they were last run.
