### ISSUE TITLE
Crash in 1.0.3.8 (64-bit) from Check for Update

### ISSUE THREAD

**Issue by JNavas2** [erickutcher/httpdownloader#156]
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	HTTP_Downloader.exe
  Application Version:	1.0.3.8
  Application Timestamp:	60710ace
  Fault Module Name:	HTTP_Downloader.exe
  Fault Module Version:	1.0.3.8
  Fault Module Timestamp:	60710ace
  Exception Code:	c0000005
  Exception Offset:	000000000001d31d
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	ffe0
  Additional Information 2:	ffe039bf55ca16c31c022e3e1addd577
  Additional Information 3:	e754
  Additional Information 4:	e7544b888c30353139f25d70673ebe25

OS Name	Microsoft Windows 8.1 Pro
Version	6.3.9600 Build 9600
System Type	x64-based PC

[ReportArchive.zip](https://github.com/erickutcher/httpdownloader/files/6289920/ReportArchive.zip)

**Comment by erickutcher** [comment]
A fix for an obscure bug caused this one to pop up. Thanks for the report.

**Comment by erickutcher** [comment]
A new version is up. You'll want to manually download it: https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.3.9

**Comment by JNavas2** [comment]
Fix confirmed, thank you!
