### ISSUE TITLE
crashing when you remove entries from download history (pressing spacebar after it)

### ISSUE THREAD

**Issue by uDEV2019** [erickutcher/httpdownloader#158]
After updating to v1.0.3.9 i've found an weird behaviour (it does exist in previous versions), for example:
having two entries in the download history and remove them with STRG+R and pressing Enter to confirm removal in the dialog.
After that, i'm pressing the spacebar and program crashes without any error message.

Windows event log (Windows 7 x64):
> Name der fehlerhaften Anwendung: HTTP_Downloader.exe, Version: 1.0.3.9, Zeitstempel: 0x607341f3
> Name des fehlerhaften Moduls: HTTP_Downloader.exe, Version: 1.0.3.9, Zeitstempel: 0x607341f3
> Ausnahmecode: 0xc0000005
> Fehleroffset: 0x000000000003a32b

After relaunch of the program, former deleted entries are back.

**Sidenote**
with previous version i've used (v1.0.3.6) it was possible to confirm the the removal dialog with spacebar.
With v1.0.3.9 this isn't possible anymore.

**Comment by erickutcher** [comment]
The crash happens when the treelistview is empty and a character is typed. It's trying to search for something when there's no entries.

I replaced all of the Windows message boxes with a custom one so they may not behave exactly the same. I'll see what I can do.

**Comment by erickutcher** [comment]
I've released a new version that fixes the crash and allows the space bar to work in message boxes. Thanks for the translation update too.
