### ISSUE TITLE
multi instance doens't support multi download  history 

### ISSUE THREAD

**Issue by feiyi1019** [erickutcher/httpdownloader#159]
This downloader is extremely light and fast . I duplicate the programe folder to serveral instances and . run the programe to carry on diffrent downloading tasks.

i find the default settings and download was set to C:\Users\HF-tech\AppData\Local\HTTP Downloader\incomplete

When sometime the programe meet a crash or system crash. then we will lose all other instance download histroy..

Can you add the function settings and histroy records to each program folder ?

thanks a lot for the great software!

**Comment by erickutcher** [comment]
If you'd like each instance to have its own settings and download history, then you can create a shortcut for each instance and put the following command at the end of the shortcut's Target path: --base-directory [path]

![basedirectory](https://user-images.githubusercontent.com/7762164/116634561-44476580-a911-11eb-9a6b-7c601314f641.png)

**Comment by feiyi1019** [comment]
thank you so much for the instruction.
