### ISSUE TITLE
Feedback for overflown list entry

### ISSUE THREAD

**Issue by char101** [erickutcher/httpdownloader#160]
Hi,

When a new entry is added via the command line or through the http server, and the number of items in the list exceeds the control height, there is no visual indicator that a new entry has been added (for confirmation). Would it be possible to add a visual indicator for such case, for example autoscrolling or adding an item count in the status bar?

Thanks.

**Comment by erickutcher** [comment]
Right now it's coded so that the first visible item always stays visible. It's a lot more efficient when it comes to adding a ton of items because I don't have to repaint the list every time an item gets added outside its visible area.

I could probably make it so that if the scrollbar is all the way to the bottom of the list, then the last item that gets added will remain visible. That would essentially cause it to autoscroll.

**Comment by erickutcher** [comment]
I ended up adding a panel in the status bar. It was easier than messing with the scroll position.

![itemcount](https://user-images.githubusercontent.com/7762164/117380343-5768b100-ae8e-11eb-9b9c-99e33b2558ed.png)

**Comment by erickutcher** [comment]
A new version is up.

**Comment by char101** [comment]
Thank you.

**Comment by char101** [comment]
I just realize that it is possible to send a mousewheel to the list control to scroll manually. Example in autoit.

```autoit
#NoTrayIcon
#include <SendMessage.au3>

const $TITLE = '[CLASS:http_downloader_class]'

func _MakeLong($LoWord, $HiWord)
  return BitOR($HiWord * 0x10000, BitAND($LoWord, 0xFFFF))
endfunc

local $url = $CmdLine[1]

local $cmd = @ScriptDir & '\HTTP_Downloader.exe'
$cmd &= ' --url "' & $url & '"'
$cmd &= ' --immediate'

local $hwnd = ControlGetHandle($TITLE, '', 'TreeListView1')
if @error then
  MsgBox(0, @ScriptName, 'Window not found')
  exit
endif

RunWait($cmd)
Sleep(100)
for $i = 1 to 5
  _SendMessage($hwnd, 0x020A, _MakeLong(0, -120), _MakeLong(0, 0))
  Sleep(10)
next
```

**Comment by erickutcher** [comment]
I added a setting in the Appearance options that'll let it scroll to the bottom of the list whenever an item is added. It'll basically perform the same action as pressing the [End key](https://github.com/erickutcher/httpdownloader/issues/162).
