### ISSUE TITLE
[Bug] Stuck on allocating if there is not enough space

### ISSUE THREAD

**Issue by char101** [erickutcher/httpdownloader#163]
Hi,

When using a temporary directory to download, and there is not enough space in the temporary directory, the download item is stuck in the "allocating" status, and there is no way to restart the download (after freeing the space in the temporary directory) because the restart menu item is disabled.

**Comment by erickutcher** [comment]
I'm surprised there was no IO error during allocation. I'm thinking I could detect the free space on the disk and prevent the download from continuing. The download's status could be changed to "Insufficient Disk Space".

**Comment by erickutcher** [comment]
Here's a preview you can try. [HTTP_Downloader.zip](https://github.com/erickutcher/httpdownloader/files/6490242/HTTP_Downloader.zip) The settings will be reset in this version.

**Comment by char101** [comment]
Thanks, I have tested it by allocating a large file using `fsutil file createnew` to make the temporary directory full, and now http downloader shows allocation failed status.

**Comment by erickutcher** [comment]
A new version is up.
