### ISSUE TITLE
Creation Date/Last Modified Date [Question]

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#166]
I have a question. When **Set date and time of file from server response** option is enabled but the server does not return date/time values I noticed different behaviour in [Free Download Manager](https://www.freedownloadmanager.org/) and [HTTP Downloader](https://erickutcher.github.io/#HTTP_Downloader):

- When I use [Free Download Manager](https://www.freedownloadmanager.org/) **Creation Date = Last Modified Date** (**Creation Date** = when the download was added, **Last Modified Date** = when the download was added);
- When I use [HTTP Downloader](https://erickutcher.github.io/#HTTP_Downloader) **Creation Date ≠ Last Modified Date** (**Creation Date** = when the download was added, **Last Modified Date** = when the download was completed);

**Screen:**

![AllDup 3 4 0 24 - 2021-05-27 - 002](https://user-images.githubusercontent.com/9025757/119745076-157fc900-be96-11eb-9cb9-af52bb69a574.png)

Is this behaviour intentional? Don't you think that when a server does not provide time/date values **Creation Date** should be equal to **Last Modified Date**?

This is not of great importance, I am just curious what you think about that.

**Comment by erickutcher** [comment]
Technically speaking, every time a byte is written to the file, it's going to be modified. So the date/time should reflect that. The program doesn't actually set the date/time unless it's supplied by the server so anything you see is what Windows does naturally when a file is opened, written to, and closed.

**Comment by smaragdus** [comment]
@erickutcher 

Thank you for the explanation. So it seems that the old version of Free Download Manager (3.9.1627) which I use as a secondary download manager in cases when HTTP Downloader encounters a problem with a certain download, somehow manages to set last modified date to be equal to creation date.

Thanks
