### ISSUE TITLE
Support for Dark mode

### ISSUE THREAD

**Issue by uDEV2019** [erickutcher/httpdownloader#168]
It would be great if you could add a dark mode on schedule

**Comment by erickutcher** [comment]
The dark mode API that Windows uses for certain window elements is undocumented. I'd be happy to implement something when it's fully supported. If I were to implement anything now, it would be a hidden option that's turned on through a command-line switch.

**Comment by uDEV2019** [comment]
For the future it will be for sure a nice enhancement.

Don't know if this helps: https://github.com/ysc3839/win32-darkmode

**Comment by erickutcher** [comment]
Yeah that's basically the only documentation on it, but it's very limited in terms of what gets set.

Here's a work in progress:

![darkmode](https://user-images.githubusercontent.com/7762164/119925985-5544c000-bf2b-11eb-8338-9e89ade7add3.png)

**Comment by uDEV2019** [comment]
👍 

For me it's not mandatory that you continue with it immediately.

**Comment by erickutcher** [comment]
Here's some more progress. I can't figure out a good way to change the white line below the menu bar. Other than that, the main window is pretty much complete.

![darkmode2](https://user-images.githubusercontent.com/7762164/120057926-fa2ece00-bffb-11eb-9226-c9e888995d23.png)

**Comment by uDEV2019** [comment]
Personally i don't use the toolbar and disabled it, but i think if it is disabled the white line appears directly ofter the grey line over columns.

**Comment by erickutcher** [comment]
I've released a regular build and a dark mode build.

The dark mode build can enable dark mode with a file called "dark_mode" in the same folder as the program. It works similarly to the "portable" file.

32-bit: https://github.com/erickutcher/httpdownloader/releases/download/v1.0.4.4/HTTP_Downloader_DM_32.zip
64-bit: https://github.com/erickutcher/httpdownloader/releases/download/v1.0.4.4/HTTP_Downloader_DM_64.zip

Dark mode will only work on Windows 10 and 11.

**Comment by uDEV2019** [comment]
looks quite good. well done 👍 🍺
