### ISSUE TITLE
Restart Download

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#17]
When a downloaded file has been deleted or it has been updated on the server it might be useful to have an option to restart the download- right-click on completed download- new context menu item (perhaps below 'Stop' command):

- **Restart**

which just re-downloads the file. If such context menu command is implemented it might also be added to the tool bar ('Restart' button, perhaps after 'Stop' button to the right- 'Start' - 'Pause' - Stop' - 'Restart').

**Comment by smaragdus** [comment]
> It's doable, but a bit involved in terms of coding.

Wouldn't such command treat the restarted download as new download just using the previously added download link and thus skipping'Add URL(s)' dialog?

Currently as a workaround I use:

- 'Copy URL(s)' command - 'Add URL(s)' command - 'Download' command;

An option to 'Restart' download would spare the user a few clicks.

**Comment by erickutcher** [comment]
Right now if the file doesn't exist and you attempt to Open File from the menus, it'll detect it's not there and prompt you if you want to redownload it. All of that is easy. It's restarting it while it's currently downloading that's tricky. I could just only allow a restart if the download is stopped, but for completion's sake, being able to restart it at any point would be nicer. Nicer, but harder.

**Comment by smaragdus** [comment]
> I could just only allow a restart if the download is stopped, but for completion's sake, being able to restart it at any point would be nicer. Nicer, but harder.

From a practical point of view for me it would be fine if 'Restart' command is not active (grayed-out) when download is unfinished, paused, stopped so 'Restart' command being accessible only for completed downloads. I really do not see why should I want to restart an active download.

**Comment by smaragdus** [comment]
Thank you for the tip about

```
The specified file was not found
Do you want to download the file again?
```
message. This really works like 'Restart'! I have not used 'Open File' command because I always move downloaded files from the default download directory. So 'Restart' command may have the same behaviour.

**Comment by erickutcher** [comment]
I ended up coding it to be able to restart for all states. It makes it consistent with other things and there might be someone who could use it for testing purposes. There's also a "Are you sure you want to..." prompt if it gets accidentally clicked.

**Comment by smaragdus** [comment]
@erickutcher 

> I ended up coding it to be able to restart for all states.

I suppose it was huge work. Thank you.

A question- if a previous download is already in the list and the user adds it as a new download- shouldn't be used the previpus download from the list in stead of adding a new one at the bottom of the list?

**Comment by smaragdus** [comment]
If the list of downloads is long searching for a particular download may not be fast- what about marking a download and typing a letter, for example 'h', which navigates to the next download in the list which starts with 'h'? This may facilitate search. What do you think?

**Comment by smaragdus** [comment]
> A Find window could be made for a later version. Seems easy enough.

'Search' window will be fine but wouldn't it be easier just to search while typing? Or this type of search (directly through download list) would be harder to be implemented?

**Comment by erickutcher** [comment]
I've made it so that it behaves like a standard Windows listview control. That is, when you start typing something, it'll select the first item it finds in the list. The problem is that it's very rudimentary and limited to the Filename column. GTK style listviews can be searched in a similar manner and they're more thorough in searching, but I've never liked how it overlays a text box on the listview.

Having a Find window will let you search not only the Filename column, but also the URL column. You could do case sensitive/insensitive searches, and have it select multiple items in one go. It's much more versatile.

**Comment by smaragdus** [comment]
> I've made it so that it behaves like a standard Windows listview control. That is, when you start typing something, it'll select the first item it finds in the list.

This is exactly what I meant.

> The problem is that it's very rudimentary and limited to the Filename column.

I usually need just the file name- I remember file names, not URLs.

> Having a Find window will let you search not only the Filename column, but also the URL column. You could do case sensitive/insensitive searches, and have it select multiple items in one go. It's much more versatile.

This sounds fantastic although it would be needed rarely I suppose. Thank you, I wouldn't dare suggest such a complex feature which would be used seldom.

**Comment by erickutcher** [comment]
Restart, Remove and Delete, and Search are all in the new release.

**Comment by smaragdus** [comment]
For me (as of version [1.0.1.0](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.1.0)) `Restart` command does not work, neither when executed from context menu, nor when executed from tool bar. It triggers `Are you sure you want to restart the selected entries?` dialog but when I confirm nothing happens. Will you please confirm?

**Comment by erickutcher** [comment]
I tried it with a stopped, paused, and downloading download and they worked, but it's apparently not restarting completed downloads. I'll have to fix that.

**Comment by smaragdus** [comment]
`I tried it with a stopped, paused, and downloading download and they worked, but it's apparently not restarting completed downloads. I'll have to fix that.`

I should have mentioned that I tried to use 'Restart' command only with completed downloads.

**Comment by smaragdus** [comment]
I confirm that restarting completed downloads works fine with version [1.0.1.1](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.1.1), thanks!
