### ISSUE TITLE
Feature Request - Remove completed once finished

### ISSUE THREAD

**Issue by bantern** [erickutcher/httpdownloader#173]
Hello,

Thought it would be handy to have an option to have downloads clear from queue upon completion automatically. Forgive me if it's there and I've somehow missed it.

Thank you!

**Comment by erickutcher** [comment]
There's an option in the Edit menu that'll let you "Remove Completed" downloads. It's not automated, but it should do the same thing.

**Comment by uDEV2019** [comment]
Simply press **ctrl+a** to mark all entries, then press **ctrl+r** to remove the entries and as last step press **space** or **enter** to confirm the removal.

**Comment by bantern** [comment]
> 
> 
> Simply press **CTRL+A** to mark all entries, then press **CTRL+R** to remove the entries and as last step press **SPACE** or **ENTER** to confirm the removal.
> 
> It costs me 1 to 2 seconds

This will have to do. Thank you for the responses, closing issue.
