### ISSUE TITLE
how to download by post content type is application/json UTF 8

### ISSUE THREAD

**Issue by feiyi1019** [erickutcher/httpdownloader#174]
the default content type was Content-Type header [application/x-www-form-urlencoded] 

is there a way to change it into application/json ,and CHARSET utf-8?

it's useless and put "application/json "on the header 

Thank you so much!

**Comment by erickutcher** [comment]
I'm not sure I understand. Are you able to provide an example download that uses the content type that you're describing?

**Comment by feiyi1019** [comment]
url:http://101.36.148.68:9200/_search/scroll?scroll=1d
post_data:{"scroll_id":"DnF1ZXJ5VGhlbkZldGNoBQAAAAAAIPHvFnZmWEhkbXdWUmxXcVhwckxjUDVSRXcAAAAAADhPYBZqWWZCNUNTOVJvS0xoTnpEZEhUTDdnAAAAAAAg8fAWdmZYSGRtd1ZSbFdxWHByTGNQNVJFdwAAAAAAOE9hFmpZZkI1Q1M5Um9LTGhOekRkSFRMN2cAAAAAACDx8RZ2ZlhIZG13VlJsV3FYcHJMY1A1UkV3"}
content-type:application/json
charset=UTF-8

preview
[https://ftp.bmp.ovh/imgs/2021/07/94d41ef14d14ed12.jpg](url)

**Comment by erickutcher** [comment]
I've made it so that manual POST downloads will require the use of the Content-Type header (if needed) rather than automatically setting it to application/x-www-form-urlencoded. That'll allow the use of any value including application/json.

I'll update the browser extensions to automatically supply the POST request's Content-Type as well.

**Comment by feiyi1019** [comment]
great job

**Comment by erickutcher** [comment]
Thank you. I will more than likely be releasing a new build this weekend. It'll have the fix implemented in it.

**Comment by erickutcher** [comment]
I've released a new version that fixes this.

**Comment by feiyi1019** [comment]
works great. thank you so much!
