### ISSUE TITLE
1.0.4.4 cannot add url via the command line

### ISSUE THREAD

**Issue by char101** [erickutcher/httpdownloader#175]
Hi,

Using version 1.0.4.4 with single instance option enabled, I can no longer add url via the command line.

I tried running

* `HTTP_Downloader.exe --url [URL]` `->` nothing happened
* `HTTP_Downloader.exe --url [URL] --immediate` `->` nothing happened
* `HTTP_Downloader.exe --url [URL] --immediate --add-stopped` `->` nothing happened

**Comment by erickutcher** [comment]
I've uploaded a new version that should fix this.

**Comment by char101** [comment]
Thanks you, adding links via the command works now.
