### ISSUE TITLE
Cannot add extension to Brave Browser

### ISSUE THREAD

**Issue by kenXengineering** [erickutcher/httpdownloader#176]
The Brave Browser does not allow use of extensions added to the browser outside of the chrome web store, for security reasons.  Would it be possible to have the HTTP Downloader extension added to the Chrom Web Store?

**Comment by erickutcher** [comment]
It's possible, but Google wants a fee and they're not getting a cent from me. You should be able to sideload the extension by turning on Developer mode and loading the unpacked extension. The only issue with this approach is that it doesn't auto-update, but I don't intend to do any major changes to the extensions so it doesn't really matter at this point.

[HTTP_Downloader_Chrome_Extension.zip](https://github.com/erickutcher/httpdownloader/files/6881744/HTTP_Downloader_Chrome_Extension.zip)

Extract the zip file somewhere. Go into Brave's extension window and enable Developer mode. Select Load unpacked and then select the extracted folder.

**Comment by kenXengineering** [comment]
Well that was easy, don't know why I didn't think of that.  Thanks!
