### ISSUE TITLE
Feature: start all stopped downloads

### ISSUE THREAD

**Issue by char101** [erickutcher/httpdownloader#177]
Hi,

Problem: I like to queue downloads in stopped state. If I want to start the downloads, I have to manually select the stopped items and click Start.

Suggestion: Since there are already buttons to batch pause and stop, it would be great to also have a button to batch start paused items.

Thanks.

**Comment by erickutcher** [comment]
That's certainly doable. I'll see what I can come up with.

**Comment by erickutcher** [comment]
I added a button to the toolbar as well as an Edit menu item that'll Start / Resume Inactive downloads. Basically it'll attempt to start or resume any download that isn't completed.

**Comment by char101** [comment]
Thank you, I have tested it and it works.
