### ISSUE TITLE
Silent Mode

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#18]
I would like to suggest a new option (perhaps new check box in 'Options' - 'General'):

- **Silent Mode**

which, if enabled, automatically starts the download after it has been added either either via 'URL drop window' or via 'Download Link' browser context menu command (when browser extension is installed). This would mean that 'Add URL(s)' dialog would be skipped. I think that this might be particularly useful if in the future the browser extensions manage to intercept the downloads directly from the browser- click on a download link- the download starts automatically without any confirmation. If you do not like the idea just close this issue.

**Comment by erickutcher** [comment]
I've got a working update to my extensions that'll intercept the browser's download and redirect it to the program. There's a new option in the extensions that'll display the Add URL(s) window or send it straight to the program. You can also disable the interception. There's still some work that needs to be done and it'll require an update to the program as well, but it seems to work nicely.

I also got it to download that link you weren't able to download properly with any download manager.

**Comment by smaragdus** [comment]
> I've got a working update to my extensions that'll intercept the browser's download and redirect it to the program.

That is a great news. I think that an option for 'Silent Mode' would be handy even if the program is not integrated to a browser (I do not use Firefox Quantum (after version 56.0) so I cannot use integration to Firefox) 'Silent Mode' will enhance adding download links via 'URL drop window' which works with any browser- after dragging and dropping the download link the download will start automatically without confirmations thus skipping 'Add URL(s)' dialog. I know that this will not work in few cases when the download link is hidden.

> I also got it to download that link you weren't able to download properly with any download manager.

Another great news.

**Comment by erickutcher** [comment]
Something like "Allow drag and drop URL(s) to download immediately" sounds good to me.

My call blocking program has a silent startup mode that causes it to start up hidden in the system tray.

**Comment by erickutcher** [comment]
I have it "Download drag and drop URL(s) immediately". The main window is also a drop window and so I don't want to distinguish one over the other.

**Comment by smaragdus** [comment]
@erickutcher 

> I have it "Download drag and drop URL(s) immediately".

Thanks.

> The main window is also a drop window and so I don't want to distinguish one over the other.

Yes, they both have the same functionality.

**Comment by smaragdus** [comment]
Unticking `Show Add URL(s) window before download` check-box allows the behaviour I would like- (downloads being added without confirmation, what I called 'silent mode'), thanks.

**Comment by erickutcher** [comment]
Just to confirm. Everything with this feature works for you?

**Comment by smaragdus** [comment]
> Just to confirm. Everything with this feature works for you?

Yes, I have used only the Chrome extension. I have not encountered any problems so far.
`Download drag and drop URL(s) immediately` option also works as expected.
