### ISSUE TITLE
Close HTTP Downloader and Shut Down PC, When All Downloads Task Completed !

### ISSUE THREAD

**Issue by shahwaliullah** [erickutcher/httpdownloader#180]
If we want to download a single file or multi files, if we want on completion of file/files, http downloader should be close and pc should be shut down automatically, so there should be option for this, please add this feature.

**Comment by erickutcher** [comment]
This feature already exits. It's in the Advanced Options. The setting is: "System shutdown action when all downloads finish".

**Comment by shahwaliullah** [comment]
Thanks
