### ISSUE TITLE
Files not downloaded to the set download directory

### ISSUE THREAD

**Issue by MrTazocin** [erickutcher/httpdownloader#183]
I have set C:\Users\User\Downloads\HTTP Downloader as my default download directory. https://imgur.com/8wgJgqQ 

But during the grabbing process, the extension auto tick C:\Users\User\Downloads instead of using my default folder C:\Users\User\Downloads\HTTP Downloader. https://imgur.com/fMlswpO

This happen either I am using Chrome or Firefox.

**Comment by erickutcher** [comment]
If you have the extensions set to "Override browser's download manager" then it'll save it to the location that you choose from within the browser or it'll use the browser's default download location.

The extensions don't use HTTP Downloader's default download directory unless you uncheck the "Download directory" box in the extensions Add URL(s) window.

I know it seems confusing. Basically, uncheck the "Download directory" box that you have circled in the second image. That'll do what you want.

**Comment by MrTazocin** [comment]
Thanks for your reply,

> If you have the extensions set to "Override browser's download manager" then it'll save it to the location that you choose from within the browser or it'll use the browser's default download location.

I had set extension based on this setting. Unfortunately, I always need to uncheck the "Download directory" for every downloads. It is good if it can stay uncheck.

**Comment by erickutcher** [comment]
In Firefox there's a setting to "Always ask you where to save files". And there's something similar in Chrome. It will set the "Download directory" to wherever you choose and it should remember the last location that it was set to the next time you download something.

If you right click on a link and select HTTP Downloader > Download Link..., then it'll bring up the Add URL(s) window with the "Download directory" unchecked.

**Comment by MrTazocin** [comment]
Thanks for the explanation. I understand now. Keep up the great work!
