### ISSUE TITLE
Feature request: Remember window position on multi-monitor setups

### ISSUE THREAD

**Issue by redactedscribe** [erickutcher/httpdownloader#185]
Each time I run HTTP Downloader, both the main window and the blue drop window are in the center of my primary screen again. This appears to be because HTTP Downloader considers the windows to be off-screen if they're not on the primary, and so their positions are reset next run. Ideally I could place these windows on any other screen, keeping them out of the way of my primary workspace, and for their positions to be remembered across runs.

Thanks (and for this great downloader too!)

**Comment by erickutcher** [comment]
I could have sworn this worked. Do you have your multiple monitors set as an extended desktop or something else?

If the program is offscreen when it's started, then it'll reposition it into the center of the nearest monitor.

**Comment by redactedscribe** [comment]
It's in extended mode, yes. It might be some quirk with the OS (running Windows 11).

**Comment by erickutcher** [comment]
When I implemented multi-monitor support, I tested it on a Windows 10 720p laptop connected to a 720p television. None of that should have made a difference, but I can try to do some more testing when I get the chance.

**Comment by erickutcher** [comment]
A new release is up that should fix this.

**Comment by redactedscribe** [comment]
It has! Thanks!
