### ISSUE TITLE
"Open Directory" opens location twice, once in file manager, once in File Explorer

### ISSUE THREAD

**Issue by redactedscribe** [erickutcher/httpdownloader#190]
There's a small issue I'm having where HTTP Downloader sends the open-in-file-explorer command and my current file manager opens (XYplorer), but after some delay, about 15-20s, the same folder opens in Windows' File Explorer too, i.e a duplicate. Not sure who's to blame in this scenario, but I thought I'd mention this in case this is something fixable on your end.

Other programs that send a command to open in File Explorer are redirected fine to XYplorer, and I have not noticed a duplicate opening in File Explorer.

Thanks.

HTTP Downloader 1.0.4.7

**Comment by erickutcher** [comment]
I wouldn't know why it's opening Explorer's window as well. The code to open a folder and highlight a file is pretty standard so if there's anything going on, then it's with XYplorer. HTTP Downloader will use SHOpenFolderAndSelectItems first and if that fails, then it'll fall back to ShellExecute (which opens the folder, but doesn't highlight the file). The code block that that code is in doesn't stall, so there should not be a 15-20 second delay. I would suspect that XYplorer's interception of one of those API calls is causing the issue.

**Comment by redactedscribe** [comment]
I'll forward this to the XYplorer dev, thanks.

**Comment by redactedscribe** [comment]
Seems to be a problem with XYplorer. Confirmed by another user too. Also, another file manager I tested didn't exhibit the bug. I'll close this issue as it looks like there's nothing wrong here.
