### ISSUE TITLE
Get Time and Date from Server

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#2]
I would highly appreciate if there is a new option to get time and date for the downloaded file from server (perhaps in '_Options_' - '_General_'):

- **Get Time and Date from Server**

which, if enabled, forces [HTTP Downloader](https://github.com/erickutcher/httpdownloader) to retrieve the time and date for the downloaded file from server (if the server supports that).

This is a rather common feature for the download managers, for example:

- in **DownloadStudio** - '_Use web server's date and time for downloaded files_';
- in **Free Download Manager** - '_Set the date of a file identical to the date specified by the server_';
-  in **Internet Download Accelerator** - '_Get date and time of file creation from the server_';

I hope that this option would be implemented in the future releases of the program.

**Comment by erickutcher** [comment]
Seems easy enough. I'll look into it.

**Comment by erickutcher** [comment]
I implemented a setting in the General settings. The program will set a file's creation, modification, and access times if the "Last-Modified" header is found.

**Comment by smaragdus** [comment]
@erickutcher 

Great, thanks, this is what I need. If pre-release tests are needed you may rely on me (my system- Windows 8 x64).

**Comment by smaragdus** [comment]
@erickutcher 

`Set date and time of file from server response` option works as expected, thank you very much for adding this very useful (for me) option, many thanks!
