### ISSUE TITLE
Update Check

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#20]
I will suggest a new feature to check for updates- 'Help' - new command:

- **Check for Updates**

If a update is available a pop-up message prompts to open download page in browser.

Further in 'Options' there might be added a new check box:

- **Check for updates when program starts**

Since I watching this project I get notifications from GitHub so I don't really need update check but I suppose that this feature might be handy to users who are not following the project on GitHub.

This has already been discussed in #19 but I will post it as separate issue with some more details.

**Comment by smaragdus** [comment]
@erickutcher 

For me update check is not of great importance. I just supposed that this might be implemented easily as HTTP Downloader would get the latest version number from the [change log](https://github.com/erickutcher/httpdownloader/blob/master/HTTP_Downloader/changelog.txt) and if the used version was not the latest one it would show a message about the available update (and even the changes in the latest version). I suppose that program's popularity may grow a bit as it now supports Windows XP. Does GitHub show you how many times has the program been downloaded?

**Comment by erickutcher** [comment]
There's no download count, but it shows page traffic and it's low. My forensic tools get the most traffic, but I don't know their download count either.

An update check is somewhat of a bulky feature. I still think it isn't worth it at this point given the amount of traffic and few updates.

I will release an update tomorrow for the tooltip notification. The new setting is in the General options with the system tray icon group of settings.

**Comment by smaragdus** [comment]
@erickutcher 

> An update check is somewhat of a bulky feature. I still think it isn't worth it at this point given the amount of traffic and few updates.

I agree, About the updates- I think that 5 new versions released in about a month does not mean slow development. Anyway, for me the program has reached maturity and it is close to perfect (as of version 1.0.1.1).

> I will release an update tomorrow for the tooltip notification. The new setting is in the General options with the system tray icon group of settings.

Thanks in advance.

**Comment by smaragdus** [comment]
@erickutcher 

In case you once choose to implement update check you may have a look how it is implemented in open source translation tool **Crow Translate** ([Website](https://crow-translate.github.io/), [GitHub](https://github.com/crow-translate/crow-translate)), for me the implementation is nice, screen:

![Crow Translate 2 3 0 - 2020-01-19 - update check - 001](https://user-images.githubusercontent.com/9025757/72673872-803a1c80-3a78-11ea-8e63-dc82bb72a0ca.png)

I suppose that you might even reuse some of the code.

Regards

**Comment by erickutcher** [comment]
I've implemented a very basic update check. It'll be located in the Help menu. When an update is found, it will allow you to add it to the Add URL(s) window for download. I don't have it automatically download or install though.

**Comment by smaragdus** [comment]
@erickutcher 

Thanks. Notification when updates are available is good enough for me (actually I get e-mail notifications from GitHub when there are new releases).

**Comment by smaragdus** [comment]
@erickutcher 

First, Happy New Year!

Today I found out I had forgotten to close this issue as update check works fine:

![HTTP Downloader 1 0 4 7 - 2022-01-02 - update - 001](https://user-images.githubusercontent.com/9025757/147890203-3a4f3b18-754c-4b78-87a9-cbdcb36a5601.png)

I have to have a look at the issues- perhaps there are more issues I have opened and have forgotten to close.

Best regards

**Comment by erickutcher** [comment]
Happy New Year to you too.
