### ISSUE TITLE
[CRASH] when attempting to Remove and Delete 2 completed downloads

### ISSUE THREAD

**Issue by JNavas2** [erickutcher/httpdownloader#200]
**Steps To Reproduce**
- 2 downloads had been completed, and a 3rd was in progress.
- Attempted to Remove and Delete the 2 completed from Context Menu.
- Program crashed.
- When restarted:
  - those 2 downloads were still listed
  - as well as a previously removed download
  - and the download in progress started from the beginning again

**Context (please complete the following information):**
 - Windows 8.1 Pro x64
 - Application Version: 1.0.4.8
 - Report Archive attached.

```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	HTTP_Downloader.exe
  Application Version:	1.0.4.8
  Application Timestamp:	61d0b024
  Fault Module Name:	HTTP_Downloader.exe
  Fault Module Version:	1.0.4.8
  Fault Module Timestamp:	61d0b024
  Exception Code:	c0000005
  Exception Offset:	000000000004ac28
  OS Version:	6.3.9600.2.0.0.256.48
  Locale ID:	1033
  Additional Information 1:	ab59
  Additional Information 2:	ab595edc8d66170b20f0681c6cd73c37
  Additional Information 3:	4b68
  Additional Information 4:	4b68761a990969f816b15653abe3f0a0
```
[ReportArchive.zip](https://github.com/erickutcher/httpdownloader/files/8228018/ReportArchive.zip)

**Comment by erickutcher** [comment]
Seems like a tricky one. I'm not able to get it to crash, but see if you can try with this debug version. It'll create a crash dump that I can use to step through the code.

[HTTP_Downloader_LS_64_1.0.4.9_Beta_1_Debug.zip](https://github.com/erickutcher/httpdownloader/files/8235947/HTTP_Downloader_LS_64_1.0.4.9_Beta_1_Debug.zip)

You'll want to run the DEBUG_HTTP_DOWNLOADER.bat file. If it does crash, then it'll dump it to the CRASH_DUMPS folder. Upload anything that it creates.

**Comment by erickutcher** [comment]
There was a similar report with regard to the Remove and Delete feature here: https://github.com/erickutcher/httpdownloader/issues/197

I'll have to study the code a little closer.
