### ISSUE TITLE
Save authentication for Website?

### ISSUE THREAD

**Issue by FeyrisTan** [erickutcher/httpdownloader#202]
Is it possible to save the Username and password for a Website? Every time I have to manually enter them.
I hope I'm just blind and have not seen the option.

Edit. Yep blind

**Comment by FeyrisTan** [comment]
New Problem:
When I try to download from said website I still get:
**The server returned an invalid response to our download request.**
It then gets added to the downloader however it says:
**Skipped**
I have to manually start it.

**Comment by uDEV2019** [comment]
You have to fill out the POST method under site maintance for the website you've added.
POST ist an request method for information to get from a server.

**Comment by FeyrisTan** [comment]
Ah thanks. I still get the initial "Invalid response" message when selecting the file in firefox but once i click download it starts automatically.

**Comment by erickutcher** [comment]
The Site Manager will allow you to save username and password information for various sites.

I'm not sure why the download would get added to HTTP Downloader while the extension ends up saying Invalid response.... That shouldn't happen. What browser are you using?
