### ISSUE TITLE
1.0.4.9 - Download issue with FlashGot: Progress Failed

### ISSUE THREAD

**Issue by TheDutchJewel** [erickutcher/httpdownloader#214]
In Pale Moon I added the latest portable version of HTTP Downloader (1.0.4.9) as download manager in the FlashGot options, with the arguments you wrote [here](https://github.com/erickutcher/httpdownloader/issues/3#issuecomment-484305643): 
> Try this:
> `[--url-list UFILE] [--cookie-string COOKIE] [--header-field Referer:REFERER] [--header-field User-Agent:UA] [--post-data POST] [--output-directory FOLDER]`

But every time a download via FlashGot is added to HTTP Downloader, the Progress status shows 'Failed':
![HTTPDownloader](https://user-images.githubusercontent.com/46184729/188073901-382a92f1-efec-4759-a246-ddf233813860.png)

However, if I then press start, the download starts just fine. 

What needs to be done for this to work properly?

**Comment by TheDutchJewel** [comment]
The problem occurs only with every first download started in a session. It does not matter if HTTP Downloader is already running or not before the download is forwarded by FlashGot.

After that first download is started by pressing the start button, all subsequent downloads start immediately.

**Comment by erickutcher** [comment]
I tried it out and was experiencing the same problem that you're facing, but then it started working properly. FlashGot wasn't sending HTTP Downloader the correct link. I can't explain why that was happening. Could be something with FlashGot or Github.

**Comment by TheDutchJewel** [comment]
I think it has nothing to do with Github, because the problem occurs also with other sources:
![HTTPDownloader6](https://user-images.githubusercontent.com/46184729/188086446-20e6bea4-21ff-4d68-a9bb-559f831be6ef.png)

Note about the image:
1. Between every download the program was closed, so every download that failed was the first one of the session.
2. All failed except the [Pale Moon download](http://rm-eu.palemoon.org/release/palemoon-31.2.0.1.win64.installer.exe) one.

**Comment by erickutcher** [comment]
I see what's happening now. The encryption command-line parameter is getting messed up. It's being set to use SSL 2.0 which most sites don't support anymore.

As a workout, you can use this for the FlashGot command-line settings:

`[--url-list UFILE] [--cookie-string COOKIE] [--header-field Referer:REFERER] [--header-field User-Agent:UA] [--post-data POST] [--output-directory FOLDER] --encryption -1`

It'll force HTTP Downloader to use the default encryption (which is TLS 2.0) and that should work.

I'll release a new version that corrects this. You'll be able to remove the `--encryption -1` parameter after that.

**Comment by erickutcher** [comment]
A new version is up that should fix this.
