### ISSUE TITLE
Dark Color Scheme for Download List (Dark Mode app)

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#216]
Currently the dark mode version of the app only applies to the window (at least for me).

Please consider making the default download list colour scheme to be dark mode too.

**Comment by erickutcher** [comment]
The Dark Mode build uses the same settings file as the regular build and so if you've used the regular build first, then it'll apply the color scheme that that used when you run the Dark Mode build.

Basically, you'll want to delete the settings file in the `%AppData%\HTTP Downloader` folder and start fresh.
