### ISSUE TITLE
Add Support for Checksum and Signature Files

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#224]
Please consider adding support for checksum checking and signature verification for files.

e.g. https://www.debian.org/download

Original File: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.0.0-amd64-netinst.iso
SHA512SUMS File: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/SHA512SUMS
Signature File: https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/SHA512SUMS.sign

It'd be really useful and make this app stand out from the crowd. 😃

**Comment by erickutcher** [comment]
I think it might be a niche feature. If anything, I'd have the program run a command after a download finishes so that it can do file verification, virus scans, etc.

For now, I'm content with where the program is at the moment. I'll consider things in the future.
