### ISSUE TITLE
 remove and delete does not delete local files

### ISSUE THREAD

**Issue by sdkljd** [erickutcher/httpdownloader#226]
1: remove and delete does not delete local files
2：Failed to download in this URL   
test url: https://mirrors.aliyun.com/freebsd/releases/i386/13.2-RELEASE/?spm=a2c6h.25603864.0.0.121e1545IDoIMe

![1](https://github.com/erickutcher/httpdownloader/assets/116957851/7868620a-efdc-44f4-879c-6812c70b8567)

**Comment by sdkljd** [comment]
version: 1.0.5.1

**Comment by erickutcher** [comment]
Failed downloads like that shouldn't create a file on the disk. You should get a warning that says "The specified file was not found." when you attempt to remove and delete it from within the program.
