### ISSUE TITLE
Pop-up Notification

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#23]
Now (as of version [1.0.1.1](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.1.1)) **HTTP Downloader** offers an option for [sound notifications](https://github.com/erickutcher/httpdownloader/issues/22#issuecomment-434560683) for the completed downloads. It is a nice option but I found all sound notifications distracting- I have even disabled all Windows sounds. I would prefer a tony pop-up notification window which shows a text message for a certain period of time that all the downloads are completed. If such pop-up notification is implemented there might be an option to choose how long it should stay open before it disappears (2, 3, 5 seconds, etc).

If you do not like the idea, or you think it requires too much work and it is not worth the effort please feel free to close this issue.

**Comment by erickutcher** [comment]
I've created a balloon style info tooltip. It'll be in the General options and will only be shown if the system tray icon is enabled. The timeout is dependent on the system. Works similar to uTorrent.

**Comment by smaragdus** [comment]
@erickutcher 

Thank you.

> The timeout is dependent on the system.

What exactly does this mean?

> Works similar to uTorrent.

I have  a very old version of µTorrent (1.7.7) and I do not know whether notifications are shown in the same way in more recent versions.

**Comment by erickutcher** [comment]
The new version has been uploaded.

I have version 2.2.1 of uTorrent and it opens a balloon style tooltip in the system tray when a download finishes. It's probably the same in yours.

**Comment by smaragdus** [comment]
Thanks for the notification:

![http downloader 1 0 1 2 - 2018-11-04 - 003](https://user-images.githubusercontent.com/9025757/47968167-8956ed80-e06e-11e8-891c-d635c1e354d7.png)

I like it.

**Comment by smaragdus** [comment]
I wonder- when the download has failed should HTTP Downloader show 'All downloads have finished.' notification?

**Comment by erickutcher** [comment]
I consider anything to be finished if it no longer has an active connection and isn't queued. I suppose I could figure out a way to distinguish the states and report them in the tooltip. I'll look into that.

**Comment by smaragdus** [comment]
> I consider anything to be finished if it no longer has an active connection and isn't queued. I suppose I could figure out a way to distinguish the states and report them in the tooltip. I'll look into that.

What about a special message for failed downloads ''The download has failed.'? Of course this is not important at all, it is just that I noticed it.

**Comment by erickutcher** [comment]
I'll have the tooltip display a list of download statuses.

Something like this:

All downloads have finished.
Completed: 8
Stopped: 2
Failed: 1
