### ISSUE TITLE
How to convert locale file back to string_list.txt ?

### ISSUE THREAD

**Issue by peter8777555** [erickutcher/httpdownloader#231]
How to convert locale file back to string_list.txt ?

I suggestion:
locale_generator.exe add /reverse option

**Comment by erickutcher** [comment]
I've updated the locale generator to convert them back to the string list. You can give this version a try: https://github.com/erickutcher/httpdownloader/raw/master/HTTP_Downloader/locale_generator/Release/locale_generator.exe

Example usage:

Generate string_list.txt from locale file:
`locale_generator.exe --locale "en-US"`

Generate locale from string list file:
`locale_generator.exe --string-list "english_string_list.txt"`
