### ISSUE TITLE
Suggestion UI : Default download directory

### ISSUE THREAD

**Issue by peter8777555** [erickutcher/httpdownloader#232]
UI:
Options --> Advanced ---> Default download directory:

.\Download
Or
%Temp%\Download

![z1](https://github.com/erickutcher/httpdownloader/assets/29886853/97e048bb-0151-4ac6-a7a7-96b78f087ad9)

**Comment by erickutcher** [comment]
I have the text boxes disabled so that weird/bad paths can't be entered. The "..." button forces the use of a file or directory dialog box in order to get a valid full path.
