### ISSUE TITLE
Suggestion : UI Alignment

### ISSUE THREAD

**Issue by peter8777555** [erickutcher/httpdownloader#233]
All Alignment to Left
or
All Alignment to Center
or
All Alignment to Right

![zzzz](https://github.com/erickutcher/httpdownloader/assets/29886853/f2bbd256-4573-47c9-a946-e497791537a9)

**Comment by erickutcher** [comment]
With the exception of the Time Elapsed and Time Remaining columns, the current alignment is pretty typical of a download manager. I modeled the ListView look after the old versions of uTorrent.

These are the lines that can be changed if you wanted to hard code the positions:

https://github.com/erickutcher/httpdownloader/blob/393c2c1ff48b1393885dd60096902cfda2713846/HTTP_Downloader/treelistview.cpp#L4317
https://github.com/erickutcher/httpdownloader/blob/393c2c1ff48b1393885dd60096902cfda2713846/HTTP_Downloader/treelistview.cpp#L4321
https://github.com/erickutcher/httpdownloader/blob/393c2c1ff48b1393885dd60096902cfda2713846/HTTP_Downloader/treelistview.cpp#L4325

You'd want to change HDF_RIGHT, HDF_CENTER, and HDF_LEFT accordingly.
