### ISSUE TITLE
Delete does NOT work

### ISSUE THREAD

**Issue by peter8777555** [erickutcher/httpdownloader#234]
Menu Delete or press DEL key does NOT work.

Suggestion:
Remove --> Remove List
Remove and Delete --> Remove List and Delete File
Delete --> Delete File
Rename --> Rename List and File

![z1](https://github.com/erickutcher/httpdownloader/assets/29886853/55e65a4a-d304-4ddd-9a56-899d39ab655e)

**Comment by erickutcher** [comment]
There was a deadlock happening and a regression from the last version. I'll have a new version up sometime this weekend.

**Comment by erickutcher** [comment]
A new version is up that should fix the delete bug. I've kept the menu names the same, however, because they're consistent with menus in Windows Explorer.

**Comment by peter8777555** [comment]
Thank you a lots.
