### ISSUE TITLE
Three suggestions

### ISSUE THREAD

**Issue by peter8777555** [erickutcher/httpdownloader#237]
![z1](https://github.com/erickutcher/httpdownloader/assets/29886853/f0d2e05e-92ac-42d7-8eee-b6bdcc8adc6b)

![z2](https://github.com/erickutcher/httpdownloader/assets/29886853/a9df24e4-a935-4e56-87c7-46d88d4874cd)

![z3](https://github.com/erickutcher/httpdownloader/assets/29886853/94a438fd-bb4c-447f-b046-a142758bfccb)

Ex:
http://www.drivesnapshot.de/download/setup.exe
http://www.drivesnapshot.de/download/snapshot64.exe
http://www.drivesnapshot.de/download/snapshot.exe
if set 100 parts download Failed.
if set 5 parts download OK.

**Comment by erickutcher** [comment]
The file server date and time is best managed by Explorer. I want to avoid turning the program into a file manager.

I might add an option for formatting the date and time column and tooltip. I'm not sure when I'd get to that though.

As for the dynamic part allocation, there's no good way to approach it. If a server limits the number of connections and the download stops/fails, then the best way to correct it after the fact is to right click on the download and select "Update Download...". From there you can update the download parts to something that works. Alternatively, you can use the Site Manager to limit the number of parts on a particular site. So in your example, you can add www.drivesnapshot.de to the Site Manager and set its maximum download parts to 5.

**Comment by peter8777555** [comment]
Thank you.
