### ISSUE TITLE
[Feature Request] Custom Path Support for HTTP Downloader Executable in Firefox Extension

### ISSUE THREAD

**Issue by Hanatarou** [erickutcher/httpdownloader#245]
Dear Erick,

I hope this message finds you well. I am writing to suggest an enhancement for the Firefox extension related to the HTTP Downloader.

I believe it would be beneficial to incorporate a feature allowing users to specify a custom path for the HTTP Downloader executable within the extension settings. This becomes particularly useful when utilizing HTTP Downloader in portable mode, as it grants users greater flexibility in configuring the tool to suit their needs.

Furthermore, it would be highly advantageous if this custom path feature supports relative paths. This added functionality would enhance user convenience and streamline the overall experience of using the HTTP Downloader through the Firefox extension.

I appreciate your attention to this suggestion and the continuous improvement of your extension. Wishing you a joyful New Year!

Best regards.

**Comment by erickutcher** [comment]
What's the custom path used for? Is it for saving the downloads? When it comes to saving downloads in specific folders, the Site Manager is probably the best solution. The extension APIs don't make it easy to select a download destination.

**Comment by Hanatarou** [comment]
Dear Erick,

No, the custom path is not for saving downloads. My suggestion was to add a feature allowing users to specify a custom path for the HTTP Downloader executable within the Firefox extension settings. It would be useful when utilizing HTTP Downloader in portable mode, as users could then point to a custom HTTP Downloader executable folder.

Furthermore, it would be highly advantageous if this custom path feature supports relative paths.

Best regards.

**Comment by erickutcher** [comment]
Do you have the server enabled in the program's settings? That's what allows the extension to communicate with the program and send it the downloads. It works regardless of whether the program is in portable mode or not. If you have multiple portable setups, then you could specify a different server port for each of them. You'd have to manually change the port in the extension's settings whenever you want to use a different portable setup, but that shouldn't be too much trouble. Other than that, I'm not sure I see what the custom path would be used for.

**Comment by Hanatarou** [comment]
Dear Erick,

Thank you! I wasn't aware of the server function; it worked. However, I still believe it would be advantageous to have the ability to set the location of the HTTP Downloader executable since the server function only works when HTTP Downloader is running in the background.

In portable mode, this won't be always true. Anyway, it's just my opinion.

**Comment by erickutcher** [comment]
If the custom path would be used to execute the program (when it's not already running), then it's not possible with the extension APIs. They don't allow you to execute external programs. The most that an extension can do is communicate with an already running program.

**Comment by Hanatarou** [comment]
Dear Erick,

Thank you again!

Best regards.
