### ISSUE TITLE
Can the settings of Add URL(s) window automatically reference the Site Manager settings?

### ISSUE THREAD

**Issue by StrollStars** [erickutcher/httpdownloader#246]
I know that `the advanced configuration settings in the Add URL(s) window will override the Site Manager settings and the default settings in the Options`. But when opening the Add URL(s)  window, can it automatically reference the settings from the site manager, unless I manually modify it? Every time I click on a web link, the Add URL(s) window appears, and I have to manually configure it each time, rendering the site manager settings ineffective.

**Comment by erickutcher** [comment]
It should automatically reference the Site Manager. There's no need to modify any of the Advanced options in the Add URL(s) window. You can think of the Site Manager as the default settings that are in the Options, but for specific sites.

**Comment by StrollStars** [comment]
@erickutcher The test just now seems to be fine. Thank you.
