### ISSUE TITLE
The deletion issue in the Site Manager

### ISSUE THREAD

**Issue by StrollStars** [erickutcher/httpdownloader#248]
1. If there are two rules, deleting the upper one will turn it into a strange site after restarting HTTP Downloader; deleting the lower one or both will bring back after restarting HTTP Downloader.
2. If there are three rules, deleting the first or second one individually will meet expectations after restarting HTTP Downloader. If deleting both the first and second together, the second one will come back after restarting HTTP Downloader. If the deletion involves the third rule, all deleted ones will come back after restarting HTTP Downloader."

**Comment by erickutcher** [comment]
I'll have a new version up by this weekend that fixes this.

**Comment by erickutcher** [comment]
A new version is up that should fix this.

**Comment by StrollStars** [comment]
@erickutcher I found another issue. For example, I launch the program, sequentially add https://github.com/ and https://raw.githubusercontent.com/. Then, I exit the program and restart it, only to find that only https://github.com/ is retained.

**Comment by erickutcher** [comment]
I can't get that to happen. Did you download the latest version? https://github.com/erickutcher/httpdownloader/releases/download/v1.0.5.6/HTTP_Downloader_64.zip

Here's the steps that I did with a fresh copy:

1. Run program
2. Open Site Manager
3. Add https://github.com/ to Site textbox
4. Click Save
5. Click New
6. Add https://raw.githubusercontent.com/ to Site textbox
7. Click Save
8. Close program
9. Run program
10. Open Site Manager

I did run the program in portable mode, but that shouldn't make a difference. You could try deleting the old `site_settings` file. It's in the `%localappdata%\HTTP Downloader` folder if you're not running it in portable mode.

**Comment by StrollStars** [comment]
@erickutcher I haven't been able to reproduce the issue indeed. I close the issue for now. If there are any new developments, I'll provide feedback. Thank you very much.
