### ISSUE TITLE
REQUEST: double click action

### ISSUE THREAD

**Issue by azev** [erickutcher/httpdownloader#27]
Request:
Option to double clicking on downloaded item:
 [  ] open containing folder
 [  ] launch file

**Comment by erickutcher** [comment]
I'm not sure if it needs to be an option. I'll see what works nicely.

**Comment by erickutcher** [comment]
So here's what I did. If you double click on a item it'll open that file. If you hold Alt and double click on an item it'll open up that file's directory.

**Comment by azev** [comment]
Very good! Thanks!

**Comment by sick13** [comment]
i think there should be an option, the reason being "what if you forget to hold down ALT"?
unintended consequences might arise by accidentally running a dangerous file "not necessarily a virus etc" just a something that alters the system or something in that manner. my opinion is there should be an option to chose, either open file or folder.

**Comment by smaragdus** [comment]
I do not need double click action- I do not think that a download manager should serve as a launcher, for me context menu items 'Open File' and 'Open Directory' are more than enough,

**Comment by erickutcher** [comment]
I suppose without some warning it could be dangerous. I don't want to add a warning. I'll make it so that it opens the folder on double click and nothing else. At the very least, the behavior is consistent with uTorrent.

**Comment by azev** [comment]
That's why I think options should be implemented here.

**Comment by sick13** [comment]
yeap,a double click or context menu should be enough

**Comment by erickutcher** [comment]
New release is up. I just made it open the download's folder when you double click. Adding an extra option seems too much to me. And it's safer this way anyway.

**Comment by sick13** [comment]
Great,thx
