### ISSUE TITLE
API for httpdownloader server?

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#279]
Thanks for making awesome software.

Is there any documentation for an API for httpdownloader server? @erickutcher 

I'd like to look into developing an Android app or a webUI interface.

**Comment by erickutcher** [comment]
There's a [function](https://github.com/erickutcher/httpdownloader/blob/83ed019f6d7680a60e48736b6be29dc4398ece0e/HTTP_Downloader_Firefox_WebExtension/download.js#L22) in the extensions that's responsible for sending the requests to the server. It just an HTTP POST request: https://github.com/erickutcher/httpdownloader/blob/83ed019f6d7680a60e48736b6be29dc4398ece0e/HTTP_Downloader_Firefox_WebExtension/download.js#L183

The payload is all in binary and each value is separated by the hexadecimal value of 0x1F.

A web based user interface would be the easiest approach as you could just modify one of the extensions to fit your design.
