### ISSUE TITLE
OwnCube/ownCloud

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#28]
I have had problems downloading files from [OwnCube](https://owncube.com/index_en.php) ([OwnCube login](https://cloud.owncube.com/login))- files are downloaded just fine but they are not named properly:

- **Example 1** - if the file name is `APNG-2018.10.10.7z` it is downloaded as `APNG-2018.10.10.7z; filename=_APNG-2018.10.10.7z_`;
- **Example 2** - if the file name is Indexer++ `Beta.exe.159484.dmp` it is downloaded as `Indexer++ Beta.exe.159484.dmp; filename=_Indexer++ Beta.exe.159484.dmp_`;

A couple of downloads:

- [Example Download 1](https://cloud.owncube.com/s/6wyzDdqYNe4okY6)
- [Example Download 1](https://cloud.owncube.com/s/tdCNsHrdcA2PzTr)

As a workaround I have to rename the downloaded files manually.

Please confirm the problem.

**Comment by erickutcher** [comment]
Yeah, the Content-Disposition header field is weird. That's where a filename can be found if the field exists.

This is what the program receives: `Content-Disposition: attachment; filename*=UTF-8''APNG-2018.10.10.7z; filename="APNG-2018.10.10.7z"`

I assumed there would only be one filename value in the field value, but apparently not. The last one is a fallback or something if UTF-8 isn't supported.

I'll have a fix by the weekend.

**Comment by smaragdus** [comment]
@erickutcher 

Of course this is not critical- I discovered the problem by chance (while checking some links of shared files) and felt obliged to notify you about it.

**Comment by erickutcher** [comment]
This should be fixed in the latest version.

**Comment by smaragdus** [comment]
@erickutcher 

> This should be fixed in the latest version.

It is, thank you!
