### ISSUE TITLE
Filesize Dialog Incorrect Label Color for Dark Mode App

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#280]
Filesize Dialog has incorrect black label when using the dark mode app.

e.g:

![bug filesize dialog](https://github.com/erickutcher/httpdownloader/assets/17044982/9abaa9f7-bcf0-4176-a548-b412b752ea7e)

**Comment by erickutcher** [comment]
I've reuploaded a fix for this:
https://github.com/erickutcher/httpdownloader/releases/download/v1.0.5.8/HTTP_Downloader_DM_32.zip
https://github.com/erickutcher/httpdownloader/releases/download/v1.0.5.8/HTTP_Downloader_DM_64.zip
