### ISSUE TITLE
Feature: Show Percentage for when allocating files

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#281]
When allocating disk space for a file please show the percentage on the progress bar.

**Comment by erickutcher** [comment]
Windows will overwrite the allocated space with zeros as a security measure before it gives you access to the file. I don't think it's possible to get a progress response while it's doing that. If you want to avoid dealing with the wait of allocating a file, then I'd set "Enable sparse file allocation" in the Advanced options.
