### ISSUE TITLE
The app doesnt update the modified date

### ISSUE THREAD

**Issue by EternalTranquility1** [erickutcher/httpdownloader#285]
When i download files, the the modified date of the file remains the same as the original date set by the autor. this is makes it hard to locate recently downloaded files when sorting by date in windows explorer, as they do not show at the top of the list. Please provide an option to either update the modified date to the current date and time when a file is downloaded or keep the original date.

**Comment by erickutcher** [comment]
Go into the Options and select Advanced. In the Advanced options uncheck `Set date and time of file from server response` and then click OK.
