### ISSUE TITLE
The saving issue in the Site Manager

### ISSUE THREAD

**Issue by StrollStars** [erickutcher/httpdownloader#286]
I saved a site in the Site Manager, but when I quit the program and started it again, the entry was gone.
BTW, does the site's URL support wildcards? such as `*` and `?`?

**Comment by erickutcher** [comment]
`*` is supported. You can do something like `https://*.example.*`

Not sure why the site manager settings didn't save. How is the program running? Portable mode or regular. And does the directory where the settings are saved have the read only flag unchecked?

**Comment by erickutcher** [comment]
I'm not able to get it to fail. Are you able to upload the site_settings file? You'll probably want to remove any usernames and passwords that are set beforehand, but make sure, if they're removed, that the same issue occurs.

Also, are you running the latest version? 1.0.5.8

**Comment by StrollStars** [comment]
I running the latest version, 1.0.5.8.
But I may have found the problem. No matter what the site is, it disappears when the proxy option is `SOCKS v5`.

**Comment by erickutcher** [comment]
Try as I might, I'm not able to recreate it. Start with a fresh install and walk me through each step. List each setting you set/type in the Site Manager and in what order. Hopefully that'll tell me what's going on.

**Comment by StrollStars** [comment]
[site_settings.zip](https://github.com/erickutcher/httpdownloader/files/15418262/site_settings.zip)
This is my site_settings file. If it still cannot be reproduced, is it related to my system? Win7 64bit

**Comment by erickutcher** [comment]
I figured out what was happening from your settings. I'll have a new version up later today.

**Comment by erickutcher** [comment]
A new version is up that should fix this.

**Comment by StrollStars** [comment]
I updated it, thank you.
