### ISSUE TITLE
Remove Completed Shortcut and maybe auto trigger?

### ISSUE THREAD

**Issue by jan-the-maker** [erickutcher/httpdownloader#287]
First amazing piece of software! I am just surprised to see no keyboard shortcut for "Remove Completed". An option to automatically  remove completed would be even better but just a shortcut would really help. I know it's not an issue but it's definitely a big bummer for me because I constantly need to navigate the menu for something that could be so much more convenient. Any chance we can get it in the future?

**Comment by erickutcher** [comment]
Perhaps I can make it Ctrl+Shift+R

I'll get around to it for the next release. Might take a little while though.

**Comment by jan-the-maker** [comment]
Great!

**Comment by erickutcher** [comment]
Here's a beta you can try.

32-bit: [HTTP_Downloader_32_1.0.6.0_Beta_1.zip](https://github.com/erickutcher/httpdownloader/files/15449473/HTTP_Downloader_32_1.0.6.0_Beta_1.zip)
64-bit: [HTTP_Downloader_64_1.0.6.0_Beta_1.zip](https://github.com/erickutcher/httpdownloader/files/15449474/HTTP_Downloader_64_1.0.6.0_Beta_1.zip)

**Comment by jan-the-maker** [comment]
THX! I download it now and will report any issues ...

**Comment by jan-the-maker** [comment]
Little feedback after using it for 2days. Works like a charm ... just one small idea. If it's easy to implement I suggest maybe to get rid of the confirmation dialog box. But regardless many thanks. Such a time saver!

I also noticed a small bug? - somehow the **Site Manager** is not reliably moving files into defined subfolders. The files just get dropped into the main folder. BUT it recognizes the Download Parts settings which is promising.  So part of the Site Manager settings are definitely used. For example, if I download a .torrent file for which I don't want to use Download Parts (so 1). And it reliable downloads .torrent from a specified site without generating multiple Download parts (in contrast to my standard parts setting). But the folder is not used that I defined. Any known workaround? My folder naming is really simple like ~/Downloads/torrents so i doubt it's my own folder name "fault".

**Comment by erickutcher** [comment]
I know the dialog boxes can be annoying, but they're consistent with the way Windows Explorer works. Maybe I'll add an override at some point.

As for the Site Manager working, are you setting the download folder in the Add URL(s) window as well? Because any value that's set in the Add URL(s) window will take priority over the Site Manager settings.

**Comment by jan-the-maker** [comment]
> I know the dialog boxes can be annoying, but they're consistent with the way Windows Explorer works. Maybe I'll add an override at some point.

Totally understand.

> As for the Site Manager working, are you setting the download folder in the Add URL(s) window as well? Because any value that's set in the Add URL(s) window will take priority over the Site Manager settings.

No i never use Advanced Options. I just deactivated my TMP Folder but it didn't change anything. I just tested again ... and found out the following:


**Created a Site Manager Entry for Ubuntu (https://cdimage.ubuntu.com) and here is what happened:**

**Using the Right Click Context Menu on the Link: (using Edge)**

- Download Starts in TMP Folder
- Finished and gets moved to **Specified Folder** (specified in Site Manager)

**Using the Browser Extension on the Link (override browsers download manager) by just clicking the link directly (using Edge):**

- Download Starts in TMP Folder
- Finished and gets moved to the **Standard Download Folder** (in Global Settings)

I made sure to also not skip the Add Dialog and Advanced Options is deactivated ... same result

**Comment by erickutcher** [comment]
What you describe sounds like correct behavior.

By using the context menu to download a link, it'll defer to the program to handle the download location, unless it's specified in the extension's advanced options. So your first test is correct.

The second test, where you directly click on the link will use the browser's (Edge's) default download location unless you have it set to show a Save As... dialog. Edge and HTTP Downloader use the Downloads folder as the default download location.

**Comment by jan-the-maker** [comment]
Ah ok, i thought the site manager could recognize the link and then match
it to the custom output folder - once finished downloading.

But not a big deal. Thanks for the keyboard shortcut that is by far the
most important one.

**Comment by erickutcher** [comment]
> If it's easy to implement I suggest maybe to get rid of the confirmation dialog box. But regardless many thanks. Such a time saver!

I've released a new version and added an Advanced option in the Options window that'll disable the message prompt when you delete, remove, restart, etc. items in the download list.

**Comment by jan-the-maker** [comment]
thx so much eric! i will visit your website now and test it

**Comment by jan-the-maker** [comment]
**Override Download List Action Prompts** :)) serious eric? I had to look 3 times till it made click in my brain.

**Comment by erickutcher** [comment]
Oh yeah, I should have mentioned the actual setting. Ha! That's it.

**Comment by jan-the-maker** [comment]
Eric one more thing. I just noticed that there is no icon to delete a download in the icon bar.  any chance you could add one? often pressing the icons to stop a download is faster than the context menu. but then i still need to right click context the download to get it removed.

**Comment by jan-the-maker** [comment]
maybe the "green +" icon could be turned to become a "red x"

**Comment by erickutcher** [comment]
The red "-" icon will remove selected downloads from the list. It doesn't delete them from the disk though. Wouldn't the keyboard shortcuts be faster anyway?

**Comment by jan-the-maker** [comment]
> The red "-" icon will remove selected downloads from the list. It doesn't delete them from the disk though. Wouldn't the keyboard shortcuts be faster anyway?

omg - you right. solved!
