### ISSUE TITLE
Copy File Name(s)

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#29]
I would like to suggest another context menu command - **Copy File Name(s)**, perhaps below **Copy URL(s)**:

- ...
- Rename
- separator
- Copy URL(s)
- Copy File Name(s)
- separator
- ...

which works like **Copy URL(s)** but just copies the file names of the downloaded files.

**Usage**
I download all files to desktop and later move them to other folder. Sometimes I cannot remember to which folder I moved some downloaded files and if I can copy the file name from HTTP Downloader searching for these files (via [Everything](https://www.voidtools.com/)) would be easier. But if you think that this feature would be rarely used and that it would clutter the context menu too much just discard this suggestion.

**Comment by erickutcher** [comment]
A workaround would be to highlight the entry and press F2 to open the rename edit box. From there you can copy the name. Instead of F2, you can click once to highlight and then click again to open the rename edit box. That's two clicks that are a second apart and not a double click.

**Comment by smaragdus** [comment]
@erickutcher 

You are right, somehow this did not occur to me- I used a poor and ineffective workaround- executing `Update Download` command and then copying the file name from the URL box but the URL does not always contain the file name. Thank you for F2 tip- problem solved. I will close this issue.
