### ISSUE TITLE
Filename problem - Wrong file already exists message / Add remove double entrys from Add-on Extension URL window

### ISSUE THREAD

**Issue by Dean-Corso** [erickutcher/httpdownloader#290]
Hi @erickutcher,

I found another problem when trying to download a file and I get the message file already exists (even when download folder is empty) but it does not and then the filename in HTTP Downloader gets changed to empty field. So it does not happen with every file just for some but why? So I can add the URL and it does display the full filename but when I start the download I get this error message. Also to rename does not work after that. Also when I rename it before download it does fail on same way. All in all for some download URLs I get that error every time. Would be nice if you could check this out some more what the problem could be in case of filenames (normal chars used no special chars).
![Error_2024-05-30_002250](https://github.com/erickutcher/httpdownloader/assets/88513086/146ed603-886a-4845-8186-f109d4c31005)

Request: Found another issue when using the Add-on / Extension "Download All xy" on any website. So in some cases I get listed double or more of the same URLs found on that website and I have to remove the double / more ones manually before I add them. My idea is just to add another button in this window to remove all double / more of the same entry's to clean up that window a little right away. Or just do a compare check before you add the found URLs into that window.

**Comment by erickutcher** [comment]
What URL causes the empty filename?

**Comment by Dean-Corso** [comment]
Below a example URL you can test the problem. 
I tried more URLs from that host and I get same file name error with all of them.
[Test URL - Direct Link](https://fries.bunkr.ru/1f867add-e649-4eb3-b425-32c0509c2d16-5aEtrsK8.pdf)

**Comment by erickutcher** [comment]
Their server is supplying a Content-Disposition header value with an empty filename. I fixed the program to ignore it.

**Comment by erickutcher** [comment]
A new version is up that should fix the file name issue. I've also updated the extensions to filter out duplicate URLs.
