### ISSUE TITLE
filename changes with download and has no file extension

### ISSUE THREAD

**Issue by uDEV2019** [erickutcher/httpdownloader#294]
When adding a link to v1.0.6.0 then the downloaded filename gets "destroyed".
Looks like the following change is the problem:
- Fixed downloading of files that have blank Content-Disposition attachment names.

**Adding the link**
![image](https://github.com/erickutcher/httpdownloader/assets/51911097/0293d03b-ddb8-4365-bd98-e468157b4263)

**link added and connecting**
![image](https://github.com/erickutcher/httpdownloader/assets/51911097/05d7e4e5-63f6-4d96-890a-b19067cc08a6)

**connected and download done**
![image](https://github.com/erickutcher/httpdownloader/assets/51911097/000e445a-5f6f-47d9-8097-ec481b4eea9b)

Complete URL in listview looks like this after download
`https://objects.githubusercontent.com/github-production-release-asset-2e65be/97348774/5facd30f-3ca7-4b22-8535-472fe187deb1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240612%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240612T155057Z&X-Amz-Expires=300&X-Amz-Signature=5214b9462574718ee0a9fe1992d1f4d7ba4029cb15ef228ebe5f00bf1bd888dd&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=97348774&response-content-disposition=attachment%3B%20filename%3DHTTP_Downloader_64.zip&response-content-type=application%2Foctet-stream`

**Comment by erickutcher** [comment]
A new version is up that should fix this.
