### ISSUE TITLE
download says complete but the file is corrupted (chrome extension)

### ISSUE THREAD

**Issue by staaandup** [erickutcher/httpdownloader#299]
try downloading a subtitle from subdl using the extension method (im using brave browser)
[subtitle link](https://subdl.com/subtitle/sd1541592/the-last-house-on-the-left)
![brave_6739jaLIsW](https://github.com/erickutcher/httpdownloader/assets/50317210/eccf0557-c1fb-45ed-bd34-1b97c0bf6247)
![HTTP_Downloader_N1Qxm2O3O4](https://github.com/erickutcher/httpdownloader/assets/50317210/8bf9195b-f494-4796-bc3b-e0d23461ac1c)
this happend to me before with another website when i tried downloading a torrent file but i cant remember and deleted the file :(

**Comment by erickutcher** [comment]
The hash value is the same whether it's downloaded directly from the browser or HTTP Downloader. The reason you're getting an error when opening the file is that it's not a zip file. It's actually a rar file. The site's distribution backend is what's messing up. If you change the extension to .rar, then it should open/extract without complaining. If you use a program like 7-Zip, then it'll extract it as is without complaining either.
