### ISSUE TITLE
Support for PowerToys Windows Composition and Layout?

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#300]
Please add support for PowerToys windows composition and layout.

Currently the app's main window ignores windows snapping in FancyZones: https://learn.microsoft.com/en-gb/windows/powertoys/fancyzones

**Comment by erickutcher** [comment]
I tried the FancyZones utility and it seems to adhere to the snapping settings. I hold Shift and drag HTTP Downloader into one of the zones and it resizes it. If I move the program out of the zone it goes back to the original size. If, however, I close HTTP Downloader while it's in one of the zones, then it retains that size when it opens up again. To avoid that you can set the http_downloader_settings file to read only.

**Comment by hl2guide** [comment]
thanks for testing it more, it also depends on the app being run as an Admin or not.

**Comment by erickutcher** [comment]
The only reason to run HTTP Downloader in administrative mode is if the Quick file allocation option is enabled. If you wanted to avoid that you could change the option to Sparse file allocation. It'll work just the same and won't require the elevated privilege.
