### ISSUE TITLE
Failed-HTTP 403 error

### ISSUE THREAD

**Issue by tanreeve** [erickutcher/httpdownloader#304]
Hello, when I try to download files from ko-fi.com (it's free mod) and dropbox.com I get an HTTP 403 error.
I am using Firefox and HTTP Downloader (v.1.0.6.2) and browser extension (v.1.0.2.9).
Files that i want to download : 
[file from ko-fi.com](https://ko-fi.com/s/908190ab66)
[file from dropbox](https://www.dropbox.com/scl/fi/tgfw7i0xcyon2kpaywieh/Terrain-Mod-v3.4-Dark-Blue-Water.zip?rlkey=ps6a508zrt4g84df6sxflyqxf&e=1&dl=0)

Error screenshot:
![error](https://github.com/user-attachments/assets/b5c645fd-a51a-40d4-bdc5-77eb7f045707)

Browser extension settings:
![extension ](https://github.com/user-attachments/assets/a37a5e96-5ac7-48b6-8311-1803d1a66272)

**Comment by erickutcher** [comment]
They both seem to work for me, although the Dropbox one took a couple of tries. Could be something with their servers.

**Comment by tanreeve** [comment]
After I tried again it turns out ko-fi.com works as it should. and for dropbox, i will try it a few times. thanks for answering.
