### ISSUE TITLE
Newly set Download Folder does not apply when using Firefox Addon

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#312]
After setting a new download folder it does not apply to new downloads when using the Firefox Addon.

![example](https://github.com/user-attachments/assets/7585b314-5f61-44e1-8cdb-aa7a306b40b7)

**Comment by erickutcher** [comment]
Do you have a default download folder set up for Firefox? The extension will use that unless you explicitly enter a download folder or have Firefox set to display a Save As... dialog box.

**Comment by hl2guide** [comment]
> Do you have a default download folder set up for Firefox? The extension will use that unless you explicitly enter a download folder or have Firefox set to display a Save As... dialog box.

@erickutcher 

Ah okay I did have Firefox set to that directory:

![Screenshot 2024-10-17 151453](https://github.com/user-attachments/assets/304ee8c2-0efd-46b5-8eec-5470eecf1e6b)

May be there could be a setting for whether the directory path gets overridden or not in the application?

Thanks for making such useful software 😀

**Comment by erickutcher** [comment]
> May be there could be a setting for whether the directory path gets overridden or not in the application?

In the extension's Add URL(s) window you can put a check in the "Download directory" checkbox and it'll use the program's default download directory if no directory is supplied. If it's left unchecked, then it'll use the browser's default download directory.
