### ISSUE TITLE
can't download  wushowhide.diagcab 

### ISSUE THREAD

**Issue by mmmmm-sbi** [erickutcher/httpdownloader#313]
from here https://github.com/thedoggybrad/wushowhide.diagcab/releases/tag/Archive

link https://github.com/thedoggybrad/wushowhide.diagcab/releases/download/Archive/wushowhide.diagcab

screen shot

![wushowhide diagcab ](https://github.com/user-attachments/assets/595c70a8-3c09-4845-899c-1e5effa37cea)

**Comment by ags1234** [comment]
Using 1.0.6.5, 32 bit
Firefox 133.0 beta2
Windows 11 64 bit

The download of that *.cab works fine for me:
`Right-click -> HTTP Downloader -> Download Link...`
The download gets passed to HTTP Downloader from the browser and the file is on my disk.

**Comment by mmmmm-sbi** [comment]
Using 1.0.6.5 32 bit / 64 bit
Firefox 132.0 32 bit
Microsoft Edge 130.0.2849.68 (Official build) (64-bit)
Windows 10 64 bit

not work

**Comment by ags1234** [comment]
Using 1.0.6.5 32 bit
Firefox 133.0 beta2 64 bit
Windows 11 64 bit

Work :))

![2024-11-02_191248](https://github.com/user-attachments/assets/76d223ad-edf9-4887-a068-013b06ca5c86)
![2024-11-02_191420](https://github.com/user-attachments/assets/a07f6ae8-c69c-4b8d-969e-3ef0e65e8b7e)

**Comment by mmmmm-sbi** [comment]
can you test windows 10 ?

**Comment by ags1234** [comment]
> can you test windows 10 ?

Unfortunately no, I only have Windows 11.
It would be interesting if you could test other browsers, see if you can download the file with those.
A browser based on Firefox: [LibreWolf 132.0.1](https://www.softpedia.com/get/Internet/Browsers/LibreWolf.shtml)
And one based on Chromium: [Catsxp 4.10.4 / 4.11.1 Beta 14](https://www.softpedia.com/get/Internet/Browsers/Catsxp.shtml)

**Comment by mmmmm-sbi** [comment]
Firefox
![firefox](https://github.com/user-attachments/assets/bb0a8c72-65f2-4e48-8d8a-60883395cd74)

**Comment by mmmmm-sbi** [comment]
chrome :
i can't download extension 
package is invalid crx required proof missing .
![chrome](https://github.com/user-attachments/assets/4af6cffe-8e04-450b-972c-2c76ecc65e8a)

**Comment by mmmmm-sbi** [comment]
firefox fixed thanks .

**Comment by erickutcher** [comment]
Yeah Chrome sucks. Anyway, you need to make sure that the server is running. You'll notice in the browser extension's message box it says, "Make sure HTTP Downloader is running and the server is enabled in its options."

`Tools > Options... `
Then click on `Server` in the options tree.
Put a check in `Enable server` and then click `Apply`.

**Comment by ags1234** [comment]
This thread should be closed, if fixed.
