### ISSUE TITLE
HTTP_Downloader_Firefox_WebExtension seems to not forward downloads to HTTP Downloader

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#33]
The extension (1.0.0.4) seems to not forward downloads to HTTPDownloader.

I've tried enabling the server (with or without authentication). Also accessing the server in the browser and am met with a blank white page.

Is there a log for extension that shows errors? Are there official steps to set this up?

![screenshot_server](https://user-images.githubusercontent.com/17044982/49022694-92f4f080-f1e9-11e8-9613-cfb9ad104244.png)

**Comment by erickutcher** [comment]
What are your settings in the extension? To have it take over the browser's download manager, you'll want to set "Override browser's download manager". If you want to manually send the program links, you can right click on a link or file to access the extension's HTTP Downloader context menu download options.

There's no log unfortunately. But it's a good sign that you're at least receiving a blank page when accessing the server through the browser. It means that it can be communicated with. Sounds like the extension might not be setup completely.

**Comment by hl2guide** [comment]
Enabling "Override browser's download manager" worked for me 💃 
Could you please consider adding an official wiki or steps to use the addon for other people?
Thanks for the awesome software 👍
