### ISSUE TITLE
Saving Download History

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#34]
This is rather a question than an issue.

If 'Enable download history' option is selected it seems that the download history is saved on program exit (if new files have been downloaded since previous session), is that true? A day ago I had to shut down the computer using the power button and the new downloads for the latest session were lost. What about every new download being immediately saved after completion in 'download_history' file?

**Comment by erickutcher** [comment]
Can't do it after each download finishes because when it saves the file it writes everything from the beginning. It would be too taxing if there's a lot of downloads.

Since the program knows when all active downloads are finished, I could have it save at that point.

**Comment by smaragdus** [comment]
@erickutcher 

> Since the program knows when all active downloads are finished, I could have it save at that point.

I said "every download" because in most cases I download one file at a time. Updating 'download_history' file after all downloads are completed is just fine.

**Comment by erickutcher** [comment]
New version is up.

**Comment by smaragdus** [comment]
@erickutcher 

Thank you!
