### ISSUE TITLE
Re-ordering Download in the List

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#36]
Please consider improving the behaviour of re-ordering downloads in the list.

E.g.
![ordering](https://user-images.githubusercontent.com/17044982/49566396-95d8a980-f97e-11e8-9e03-0302a51239f4.png)

Currently there is no visible feedback for re-ordering, the download doesn't move/down up the list. It seems to re-order in the background.

Is the # column an index (download ID) or the ordering?
Maybe there should be a list item click-and-drag functionality to reorder items, or pressing Ctrl+PgUp or Ctrl+PgDn for selected item(s)?

Thanks for making worthwhile software 💃

**Comment by smaragdus** [comment]
@hl2guide 
You may look at #10 and especially [this](https://github.com/erickutcher/httpdownloader/issues/10#issuecomment-425753207).

**Comment by erickutcher** [comment]
Revamping the queue like this would be a large undertaking and I'm in need of a break. But I'll consider it for the future.
