### ISSUE TITLE
Ability to verify that a download completed correctly

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#37]
Please consider adding the ability to check if a download completed correctly.  **[Data received fully intact]**

_Maybe a checksum (SHA-3) against an expected checksum for each download and a byte-based count check?_

This would improve confidence and reassure users 👍

**Comment by erickutcher** [comment]
It would be best to use an external tool for this since the HTTP protocol doesn't send or require a hash/checksum value. You'd have to get the value from the site that you're downloading from (if they supply it) and compare it after.
