### ISSUE TITLE
Add URL(s) Dialog - Remember Dimensions and Position

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#39]
Please consider having the **Add URL(s)** dialog remember dimensions and position, maybe the main window too?

**Comment by erickutcher** [comment]
The main window should already remember its size and position.

I'll see what it's like for the Add URL(s) window.

**Comment by erickutcher** [comment]
The Add URL(s) and Search windows will now retain their size and position while the program is running. Unlike the main window, however, they'll reset to default when the program is restarted.

**Comment by hl2guide** [comment]
Thanks so much for fixing this in the latest release 🥇
