### ISSUE TITLE
Download Directory not being set?

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#41]
There seems to be a bug with adding a download in the newest version.
_The download directory seems to be not set properly._

![pic](https://user-images.githubusercontent.com/17044982/51715945-e7eca000-208e-11e9-966b-1cfaee70554f.jpg)

I've tested with setting it to C:\Temp or the **downloads** folder but it prompts in both situations. (both exist)

**Comment by erickutcher** [comment]
It should be corrected in the latest release: https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.1.7

**Comment by erickutcher** [comment]
Yeah, it's still a problem. I see what's going on.

**Comment by erickutcher** [comment]
This should be fix this time. Sorry about that. https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.1.8
