### ISSUE TITLE
Progress in task bar icon?

### ISSUE THREAD

**Issue by hl2guide** [erickutcher/httpdownloader#42]
Please consider adding a progress indicator to the taskbar icon for HTTP Downloader.
This would allow the app to be minimized and still show the status.

e.g (pink border):
![preview](https://user-images.githubusercontent.com/17044982/51885871-8f483a80-23e1-11e9-87ca-20a43d0a9963.jpg)

The bar could indicate the "percentage completed for active downloads in the list".

Green could show it's active, yellow for paused and red for "an error has occured" (download failed etc).

**Comment by erickutcher** [comment]
This is something I've considered in the past. It'll only work for Vista and above I believe. The problem I saw was having to deal with multiple downloads. I'll think of something.

**Comment by erickutcher** [comment]
New version is up.
