### ISSUE TITLE
History Editor - Icon

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#45]
I have briefly tested **HTTP Downloader History Editor** (version [1.0.0.0](https://github.com/erickutcher/httpdownloader/releases/tag/HDHE_v1.0.0.0)), it seems to work fine, thanks.  I would like to suggest that you embed the **HTTP Downloader** icon in the executable (**HDHistoryEditor.exe**) and in the title bar, screen:

![http downloader history editor 1 0 0 0 - 2019-02-15 - 002](https://user-images.githubusercontent.com/9025757/52823269-fbeb5680-30bc-11e9-8ec6-d4b4f3ce6d59.png)

With icons embedded in the executable and in the title bar the program would look slightly better. I suppose this is very easy to be implemented.

**Comment by erickutcher** [comment]
Here's a new version that has the icon: https://github.com/erickutcher/httpdownloader/releases/download/HDHE_v1.0.0.1/HDHistoryEditor.zip

This program was just something simple enough to view the files. I don't really intend to expand on it. The only time I'll be updating it is if I need to change the format of the history files.

**Comment by smaragdus** [comment]
@erickutcher 
Thanks! The program is good enough. It is just that I do not like iconless programs. It stores no settings anywhere, right?

**Comment by erickutcher** [comment]
It doesn't save any settings.
