### ISSUE TITLE
Request: Progress bar colour customization

### ISSUE THREAD

**Issue by chocolatechipcats** [erickutcher/httpdownloader#47]
A cosmetic change that would be appreciated is the option to change the colour of the progress bar. Thanks in advance, and great program.

**Comment by erickutcher** [comment]
Are you referring to the progress bar in the taskbar, or the ones in the download list? The taskbar progress bar only has green, yellow, and red available for it. I can change the ones in the download list though.

**Comment by chocolatechipcats** [comment]
> Are you referring to the progress bar in the taskbar, or the ones in the download list? The taskbar progress bar only has green, yellow, and red available for it. I can change the ones in the download list though.

Download list. Sorry, should've been more specific!

**Comment by erickutcher** [comment]
In the next release you'll be able to change the color of the progress bar for the various progress states (Connecting, Downloading, Paused, Stopped, etc.). You'll also be able to stylize odd and even rows with various colors and fonts.

**Comment by erickutcher** [comment]
A new version is up. You can change the colors and fonts of the download list under the Appearance tab in the Options.
