### ISSUE TITLE
Single Instance

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#5]
I discovered that the user can start multiple instances of HTTP Downloader. This is not bad but you may add new check-box in 'Options' (perhaps in 'General' tab):

- **Single Instance**

which, if checked, will allow only a single instance of HTTP Downloader to be started.

**Comment by erickutcher** [comment]
This is in the General options. Pretty self explanatory.

I added a command-line switch "-u" that will let you add a URL when starting the program. If there's already an instance running (and the option is enabled for one instance), it'll pass the URL to the existing program.

**Comment by smaragdus** [comment]
'Allow only one instance of the program to run' works as expected, thank you.
