### ISSUE TITLE
Error in downloading pdf file when using Squid HTTP proxy server

### ISSUE THREAD

**Issue by san-r** [erickutcher/httpdownloader#50]
In my workplace, internet connection is shared in office LAN through Squid proxy server. I have downloaded several binary files (zip, exe, msi etc.) using HTTP Downloader through multiple computers in office LAN through proxy without any issues.

However, when I tried the following url [http://www.iitk.ac.in/ce/test/IS-codes/is.4905.1968.pdf](http://www.iitk.ac.in/ce/test/IS-codes/is.4905.1968.pdf) it downloaded a file with the same name as expected, ie, "is.4905.1968.pdf" but it was something completely different. It was actually an html page with the following content (copied and pasted here with some loss of formatting):

```
ERROR
The requested URL could not be retrieved

The following error was encountered while trying to retrieve the URL: /ce/test/IS-codes/is.4905.1968.pdf

    Invalid URL

Some aspect of the requested URL is incorrect.

Some possible problems are:

    Missing or incorrect access protocol (should be "http://" or similar)

    Missing hostname

    Illegal double-escape in the URL-Path

    Illegal character in hostname; underscores are not allowed.

Your cache administrator is admin@localhost.

Generated Tue, 26 Mar 2019 12:15:06 GMT by OfficeServer (squid)

```

It's actually an error message by the Squid proxy server and it's an Invalid URL issue.

I then tried to download the above URL through Flashget, Flareget and aria2c (with proper proxy settings) and all three downloaded the file properly without any problem. So this issue seems to be with HTTP Downloader only.

Please check. Thanks.

**Comment by erickutcher** [comment]
This could be tricky to debug on my end without knowing the proxy server setup and settings. I'd have to recreate it on my end to test. The URL works without going through any proxy.

Explain how you have HTTP Downloader configured. Are the Proxy settings in the Options window set? The HTTPS proxy settings should probably be disabled.

**Comment by erickutcher** [comment]
I figured it out. It's not sending an absolute URI to the proxy. It'll be fixed in the next release.
