### ISSUE TITLE
Downloads from Icedrive fail

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#53]
Downloads from [Icedrive](https://icedrive.net/) fail resulting in **404** file, screens:

![HTTP Downloader 1 0 2 1 - 2019-04-23 - error - 002](https://user-images.githubusercontent.com/9025757/56534669-d1a59180-6562-11e9-8bdc-d781be73b645.png)

![HTTP Downloader 1 0 2 1 - 2019-04-23 - error - 003](https://user-images.githubusercontent.com/9025757/56534697-dd915380-6562-11e9-8f8a-86ee6ae714bf.png)

This is a publicly shared file:

[Link](https://icedrive.net/0/49Q48fdfbr) (`https://icedrive.net/0/49Q48fdfbr`)

This is the download link I got from **HTTP Downloader** (version **1.0.2.1**):

`https://icecube-03.icedrive.io/download?p=T8V8YK5vkJfBvfJXretnpLkgu8vk2z+DIvlQMvvoht8DVq5wwBOQemcEPQi8WwkeCdfNgjR3ABjR8qpCtABssxVwjwTRou2BXCNYenP2nM2iZymz4s2dqOHaM8nqPPemWxX7FHlHnSIK7y/a+c+/21HJz/u34bL10e82zD9+KCSdv4Me5U6v8P/VOF4DXyObziHzfnhtusE+k7K6hHCTRl8la84N3QnmBDYCthNqo2kVrB5KWbbOmUlyQfUz8+2I`

I was able to download the file using another download manager. This is the download link I got from the other download manager:

`https://icecube-03.icedrive.io/download?p=T8V8YK5vkJfBvfJXretnpLkgu8vk2z%2BDIvlQMvvoht8DVq5wwBOQemcEPQi8Wwkeb3ZOoieei1NJX3ot5wMJAxXNZb5Ihjq9mpnYXrT%2F9lm7qqjlzlxpw6M6fZYl1TAZ3j%2BPA6rBBAi%2BJD5PXDVpxW1ofeqFlG4wakXFymqpPBoB%2BuaUHZd6HXMdtIYoFXB0UeiXQMAVqmQsI0EX18D92ihEpzpIvwOIGkwngsigPFQqir9oYcV9pk15xRXRfjBo`

When I copied this link and pasted it into **HTTP Downloader** the download was completed successfully, screen:

![HTTP Downloader 1 0 2 1 - 2019-04-23 - error - 005](https://user-images.githubusercontent.com/9025757/56535085-a4a5ae80-6563-11e9-95f1-bfb046bb15cc.png)

It seems that **HTTP Downloader** does not retrieve the right download link.

If needed I can post more **Icedrive** links.

**Comment by erickutcher** [comment]
It appears that the URL parameters values need to be percent encoded.

**Comment by erickutcher** [comment]
In version 1.0.1.9 I added code that decodes the URL(s) that are sent from the extensions so that any percent encoded (Unicode) filenames could be displayed correctly. It wasn't necessary to do that, given some other changes I made later, so I've reverted the code.

Should be fixed in the next version.

**Comment by smaragdus** [comment]
@erickutcher 

> Should be fixed in the next version.

Thank you.

**Comment by smaragdus** [comment]
@erickutcher 

Downloading files from [Icedrive](https://icedrive.net/) works fine with the latest versions of HTTP Downloader and Chromium extension, thank you.
