### ISSUE TITLE
Downloads from magnet2torrent.com fail

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#54]
**Issue**

All the downloads from [magnet2torrent.com](http://magnet2torrent.com/) fail, in stead of a torrent file HTTP Downloader gets a 3 KB `magnet2torrent.com` file, screen:

![HTTP Downloader 1 0 2 1 - 2019-04-29 - 002](https://user-images.githubusercontent.com/9025757/56881583-91b24300-6a69-11e9-8516-7e3750df3c19.png)

**Reproduce**

- Open [The Pirate Bay](https://thepiratebay.org/) website;
- Copy a magnet link;
- Open [magnet2torrent.com](http://magnet2torrent.com/) website;
- Paste the magnet link;
- HTTP Downloader does not download the actual torrent file;

**Workaround**

When I need to get a torrent file from  [magnet2torrent.com](http://magnet2torrent.com/) website I have to disable browser integration. This is not much of a problem but it would be better if HTTP Downloader could handle these downloads.

**Comment by erickutcher** [comment]
So this is a Chrome extension issue. Apparently there's a property of the download item called "finalUrl" that contains the last redirected URL of a request. I found it strange that the problem wasn't happening if Firefox. It's an easy fix though.

**Comment by smaragdus** [comment]
@erickutcher 

I forgot to mention that I meant integration with Chromium-based browsers. My Firefox version is older so I cannot use Firefox extension. Thank you for the fix!

**Comment by smaragdus** [comment]
@erickutcher 

I could not test the latest version of Chromium extension ([1.0.0.7](https://github.com/erickutcher/httpdownloader/releases/tag/CE_v1.0.0.7)) with [magnet2torrent.com](http://magnet2torrent.com/)
because pasting a magnet link currently redirects to [another site](https://www.limetorrents.info/). But I tested the extension with a similar site- [magnet2torrent.me](http://magnet2torrent.me/) and the download was successfully completed.

Thanks
