### ISSUE TITLE
Iridium - extension not installed

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#58]
I decided to try [Iridium](https://iridiumbrowser.de/) ([GitHub](https://github.com/iridium-browser)) and I got the following error message:

`Apps, extensions and user scripts cannot be added from this website`

**screen:**

![Iridium 2019 4 73 0 - 019-05-13 - 004](https://user-images.githubusercontent.com/9025757/57597158-f041eb80-7556-11e9-888e-a28dc90113a0.png)

I extracted the extension, packed it and tried to install it again, which resulted in the following error messages:

`This extension is not listed in the Chrome Web Store and may have been added without your knowledge.`

**screen:**

![Iridium 2019 4 73 0 - 019-05-13 - 007](https://user-images.githubusercontent.com/9025757/57597856-b4f4ec00-7559-11e9-9412-23d8b596bc8f.png)

**screen:**

![Iridium 2019 4 73 0 - 019-05-13 - 008](https://user-images.githubusercontent.com/9025757/57597885-cf2eca00-7559-11e9-8b8f-8a7c0e2a7685.png)

I am aware that this is not an issue of **HTTP Downloader Chrome Extension** but of **Evil Chromium** yet I would like to ask- is there a better workaround than unpacking the extension and loading it?

**Comment by erickutcher** [comment]
The only real solution is to upload it to the Chrome Web Store. They want you to pay a fee to have a developer account on there. No thanks.

**Comment by smaragdus** [comment]
@erickutcher 

Thank you for the confirmation. If I were a developer I would not like to submit my extensions to Play Store prison either because supporting walled gardens would be against my principles.

Disabling extensions that are not listed in Play Store is not just about money- it is more about control, Evil Google wants total control upon the developers and the upon users altogether- it decides what features are allowed, (Google does not allow extensions downloading YouTube content for example, which ruined many extensions, while downloading from YouTube is now more exigent and necessary than ever as Google bans users, deletes accounts and videos- what is available today is likely to be gone tomorrow), which extensions are permitted (Google often bans extension for no apparent reason) what extensions the users can install and use. I suppose that it is only a matter of time that privacy extensions would fall prey to the tyrannical monstrosity Google. Attacking both the developers and the users Google attacks general freedom turning the internet into a jail (Goolag). Actually Mozilla is no better than Google as it is closely following all evil Google practices.

The situation with modern browsers is catastrophic- not only they are all terrible- bloated, heavy, slow (which is amazing having in mind that almost all once useful features have already been removed) but they are also a privacy disaster as they track the users in all possible ways. It seems almost impossible to find a browser that does not track the users (there are several, but they are developed by single developers or very by very small teams so that the development is very slow). Even Vivaldi tracks users and feature-wise it is just a shadow of the classic Opera. For me it is hard to tell which is worse- Chrome or Firefox, yet I would say Firefox because once it was great but it was totally ruined, now it is absolutely unrecognizable compared to the highly customizable and powerful browser it once was (I used to list the features Mozilla had removed but lost count and gave up).

Having said all that I would like to ask- would it require a lot of work to create an extension for XUL-based, pre-Quantum browsers such as SeaMonkey, PaleMoon, K-Meleon, etc.

I would close this issue as there is no real solution as you said. Also, it seems almost impossible for a small team to release a totally un-Googled version of Chromium- its code is so huge and complex that it looks more like an OS than a browser and I doubt that there is a single developer capable of understanding the whole Chromium code in total.

**Comment by erickutcher** [comment]
I'm not sure how much work it would involve to create a XUL based extension, but I don't want to have to support another extension. Plus, I have a lot of other projects that I've been meaning to upload on here and those have been taking up my time at the moment.

**Comment by smaragdus** [comment]
@erickutcher 

> I'm not sure how much work it would involve to create a XUL based extension, but I don't want to have to support another extension.

No problem at all, I was just asking. Furthermore, I know that there are some still active developers of Palemoon add-ons so I might ask in the Palemoon forum whether one is willing to create an add-on for Palemoon.

> Plus, I have a lot of other projects that I've been meaning to upload on here and those have been taking up my time at the moment.

You mean you are working on new programs?

Regards

**Comment by erickutcher** [comment]
> You mean you are working on new programs?

I'm revamping my 56K call blocker, and also writing a simple command-line Google Authenticator.

**Comment by smaragdus** [comment]
I found a bit more tolerable version of Firefox- [Iceweasel](https://sourceforge.net/projects/libportable/), screen:

![Iceweasel 66 0 3 - 2019-05-16 - 005](https://user-images.githubusercontent.com/9025757/57826922-01d10080-77ae-11e9-94d2-1b9589b9f928.png)

To make it portable I guess one needs to rename

`portable(example).ini`

to

`portable.ini`

Yet for me HTTP Downloader works better with Chromium-based browser because I do not know how to avoid confirmations for every single new download.
