### ISSUE TITLE
Drop Box

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#6]
Adding download links manually works fine but this is not the handiest way to pass downloads to a download manager (especially when browser integration does not work which is the case for me). I know that **HTTP Downloader** supports 'Drag&Drop' and 'Always on Top' but I think that it would be easier if the program offers a drop box (also called drop basket)- a tiny square box to which the user may drag&drop download links and it opens 'Add URL(s)' dialog.

**Usage**

- 'Drop Box' can be enabled from menu bar ('View') or from tray menu ('Show Drop Box' or just 'Drop Box');
- 'Drop Box' can be moved on desktop and last used position is remembered after restart;
- 'Drop Box' can have the same context menu commands like tray menu;
- When a download link is dragged and dropped to 'Drop Box' it opens 'Add URL(s)' dialog;

**Advantages**

- Dragging and dropping download links to 'Drop Box' would be faster than copying the link and pasting it in **HTTP Downloader**;
- A tiny square (the 'Drop Box') being 'Always on Top' would be handier for dragging and dropping of links than the whole program window being 'Always on Top';

**Comment by erickutcher** [comment]
While this wouldn't be difficult to do, I'm actually not a fan of that sort of feature. Do you know of any Microsoft created programs that behave that way and that I could base the design on? I try to do things by their standards so that my programs look native to the system.

**Comment by smaragdus** [comment]
Perhaps I should have shown an example first:

![drop boxes - 2018-10-01 - 002](https://user-images.githubusercontent.com/9025757/46283552-60c66a00-c57d-11e8-847d-674fb104e5ff.png)

1. Free Download Manager
2. AWGG
3. DownloadStudio
4. Internet Download Accelerator

I cannot give Microsoft example because to my knowledge it has released a single download manager- [Microsoft Download Manager](https://www.softpedia.com/get/Internet/Download-Managers/Microsoft-Download-Manager.shtml), which does not have such feature and is generally so poor that it is not worth mentioning. 

I think that 'drop box' is a common feature for the download managers. What makes it useful is that it offers a fast and easy way to pass the download to the download manager (especially when the download manager is not integrated to the browser). There is no copying of download links, no opening the download manager main window- when the link is dropped to the 'drop basket' it automatically opens 'Add Download' dialog. For me such 'drop basket' is handier than the whole program being 'Always on Top'- it occupies tiny space and the user can always drag and drop a link onto it.

This feature is specific to download managers and that is why it is not common among other types of programs. If you do not like the feature there is no problem to discard it. In fact I think that 'drop box' is the most useful feature I have ever suggested because it spares the user some steps to add download links (for me dropping a link is faster than copying and pasting a link and it is handier tiny 'drop box' to be on top in stead of the whole program). But you are the developer and your decide the design of the program.

**Comment by smaragdus** [comment]
It occurred to me that I had seen a bookmark manager utilizing this feature- adding links to it via a drop box- [StorURL](https://www.haztek-software.com/applications/www/storurl/), the 'drop box' is called 'Floating Toolbar' and it can be enabled via 'View' menu or via 'CTRL+SHIFT+T' key combination. If you are curious you may check how it works (using the portable version of the program).

**Comment by erickutcher** [comment]
This can be enabled/disabled from the General options.

You can drag it wherever and it'll snap to the edge of the screen. It's also semi transparent when not hovered over.

It'll accept anything the main window does including download_history files.

**Comment by smaragdus** [comment]
@erickutcher 

The 'drop box' or as you call it 'URL drop window' was the feature I desired most and I am really happy that you implemented it. I tested it and it worked flawlessly, excellent work, many thanks!

I am curious- do you personally like this 'URL drop window'? Do you find it very useful? For me it is faster than using the browser context menu (when the program is integrated into the browser) and than using the 'Add URL(s)' dialog. Snapping to windows edges is cute and handy too. It remembers its position on desktop and the colours you choose are nice. In short- great work!

Thank you very much, Eric!

**Comment by erickutcher** [comment]
I manually copy and paste links or use my browser extensions context menus to filter out things. What I download is usually hidden behind javascript and so dragging and dropping isn't a common thing for me. But I'm glad you like the feature. I do see its merits.

**Comment by smaragdus** [comment]
This is rather cosmetics than real issue- I use HTTP Downloader with 'URL drop window' always on but when I need distraction-free, full screen view I have to disable it which currently requires 3 clicks:

1. right-click either tray icon or 'URL drop window';
2. open 'Options'
3. uncheck 'Enable URL drop window';

If this can be done from tray icon context menu or from 'URL drop window' context menu it would require 2 clicks:

1. right-click either tray icon or 'URL drop window';
2. uncheck 'Enable URL drop window';

This is not complaint, just observation.

**Comment by erickutcher** [comment]
Here's what I did.

The drop window's context menu has "Always On Top" to toggle the window's z-order. You can also middle click the window to toggle it. When it's always on top, the border around the window will be black. When it's not on top (normal z-order), the border will be a cyan color.

Double clicking the drop window will open up an Add URL(s) window.

I thought about different ways of approaching this and it seemed the most convenient. The problem with simply hiding the window is that it would have to be shown from a system tray menu item, or from the main window's menu if the system tray isn't enabled. That doesn't seem obvious to me. Disabling the drop window would follow the issue. Messing with the z-order seemed a reasonable way to go about it.

**Comment by smaragdus** [comment]
This is quite interesting. I will have to see how it works. I am more than pleased with the URL drop window so if I am so lazy to go to options I can just exit the program from tray. What I suggested was derived from Free Download Manager (in fact most of my ideas were borrowed from it):

**tray icon**
![free download manager 3 9 7 build 1627 - 2018-10-20 - 002](https://user-images.githubusercontent.com/9025757/47259611-4add0280-d4b4-11e8-8ab4-516fd0e53384.png)

**view menu**
![free download manager 3 9 7 build 1627 - 2018-10-20 - 004](https://user-images.githubusercontent.com/9025757/47259616-60522c80-d4b4-11e8-938d-afd856ef04ce.png)

Another possible solution might be if you assign a shortcut key which toggles URL drop window on/off (perhaps 'CTRL+U', 'CTRL+D') but such a shortcut key should be bound to 'Enable URL drop window' check-box in options.

**Comment by smaragdus** [comment]
'Always on Top' option is excellent solution- fast and handy, the problem is solved in the best possible way, thanks for the idea and the implementation!

**Comment by smaragdus** [comment]
@erickutcher 

The URL drop window is absolutely awesome- for programs I update often I keep text files with direct download links and dragging and dropping a link from a text editor into the URL drop window works as good as doing the same from a browser- this is excellent!
