### ISSUE TITLE
Bug: Remove Complete menu item doesn't work

### ISSUE THREAD

**Issue by t214c** [erickutcher/httpdownloader#61]
Steps to reproduce:
- Edit -- Remove complete
- File -- Exit
- Reopen

Expected behavior:
- All complete downloads removed

Current behavior:
- Complete downloads remain

![1](https://user-images.githubusercontent.com/41517489/59246687-5769c300-8c1d-11e9-8840-9f60f023045e.png)
![2](https://user-images.githubusercontent.com/41517489/59246688-58025980-8c1d-11e9-8fdf-b5140197b9aa.png)
![3](https://user-images.githubusercontent.com/41517489/59246689-58025980-8c1d-11e9-9ae4-c477b674d637.png)
![4](https://user-images.githubusercontent.com/41517489/59246690-58025980-8c1d-11e9-8910-2ca89c3afd41.png)

**Comment by erickutcher** [comment]
Nice catch. I'll have this fixed by the weekend.

**Comment by t214c** [comment]
Thanks
