### ISSUE TITLE
dotepub extension

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#63]
When 'Override browser's download manager' option is enabled in Chromium extension the EPUB files generated by **dotepub** extension ([Website](https://dotepub.com/), [Chrome Store](https://chrome.google.com/webstore/detail/dotepub/okpfiebkkmjcnodegbbbiellepfhoglm), [Firefox Store](https://addons.mozilla.org/en-US/firefox/addon/dotepub/)) the downloads fail- I get empty **post** file. As a workaround I disable 'Override browser's download manager' option. It would be convenient if **HTTP Downloader** knows that it should skip these downloads. If this cannot be fixed it won't be a great problem for me- I will just disable 'Override browser's download manager' option when I need to get such EPUB files generated by **dotepub**.

**Comment by erickutcher** [comment]
The HTTP Downloader extensions will attempt to get POST data after it's been made so that it can include it in the download request. If some other request happens after that, then the data gets erased. I think that's what's going on here. It does work, but it's not consistent.

I'll have to figure out a more reliable way to get the POST data.

**Comment by smaragdus** [comment]
Now when trying to get files created by **dotepub** with **HTTP Downloader extension** enabled (`Override browser's download manager`) I got the following error:

![snipaste-2019-06-17_014745](https://user-images.githubusercontent.com/9025757/59570553-be1a3100-90a2-11e9-984f-19255c697306.png)

It seems that **HTTP Downloader** cannot get the file name from **dotepub**:

![snipaste-2019-06-17_015056](https://user-images.githubusercontent.com/9025757/59570563-dd18c300-90a2-11e9-8f29-04b692b510f7.png)

Using the previous version (**1.0.2.2**) I was getting an empty file, now using the current version (**1.0.2.3**) I get no file. As I mentioned before this is not a big problem and there is an easy workaround- disabling `Override browser's download manager` option.

**Comment by erickutcher** [comment]
Nothing changed in the latest version with regard to the extensions and connection related code. The time out error would mean that the extension can't connect to HTTP Downloader's web server. Make sure it's still enabled in the options and that the settings for it and the extensions match.

**Comment by erickutcher** [comment]
I've updated the extensions now and they should handle getting the correct POST data from the dotepub extension.

**Comment by smaragdus** [comment]
@erickutcher 

I updated the both extensions to version **1.0.0.8**:

**Chromium:**

![HTTP_Downloader_Extension 1 0 0 8 - 2019-06-18 - Chrome - 004](https://user-images.githubusercontent.com/9025757/59717212-3bb77b80-9220-11e9-8be5-95c359723000.png)

**Firefox:**

![HTTP_Downloader_Extension 1 0 0 8 - 2019-06-18 - Firefox - 003](https://user-images.githubusercontent.com/9025757/59717259-4eca4b80-9220-11e9-918a-1a4248864b3d.png)

and I still get the same download error:

**Chromium:**

![HTTP_Downloader_Extension 1 0 0 8 - 2019-06-18 - Chrome - 001](https://user-images.githubusercontent.com/9025757/59717400-94871400-9220-11e9-85c1-046fc313f11a.png)

**Firefox:**

![HTTP_Downloader_Extension 1 0 0 8 - 2019-06-18 - Firefox - 001](https://user-images.githubusercontent.com/9025757/59717434-a8327a80-9220-11e9-8437-0a1f7eb02305.png)

This is the file **HTTP Downloader** could not fetch:

![HTTP_Downloader_Extension 1 0 0 8 - 2019-06-18 - Chrome - 002](https://user-images.githubusercontent.com/9025757/59717515-d1530b00-9220-11e9-92d3-23672336dbda.png)

This connection time-out happens only when I try to get a file produced by **dotepub**, all other downloads are completed just fine. I really do not know what is going on.

**Comment by smaragdus** [comment]
I supposed that some other installed extension might be preventing HTTP Downloader extension to work fine so I run another portable instance of [Cent Browser](https://www.centbrowser.com/) wit only two extensions - HTTP_Downloader_Chrome_Extension and dotepub- the same result.

Then I decided to check the HTTP Downloader settings and in Connection tab when I switched from **Hostname / IPv6 address** to **IPv4 address** the EPUB file generated by dotepub was downloaded fine. It seems that HTTP Downloader can retrieve the EPUB files generated by dotepub when **Hostname / IPv6 address** is used. Can you confirm this?

The other good news is that Cent Browser allowed me to install the CRX file directly without the need to use Load unpacked. After the installation I had both version 1.0.0.7 and version 1.0.0.8 so I removed version 1.0.0.7. As I mentioned above all files are downloaded right.

I will close this issue as now I can get files generated by dotepub. Thank you!

**Comment by erickutcher** [comment]
That's strange that the hostname doesn't work, but IPv4 does. The default hostname is "localhost" which should be equivalent to 127.0.0.1 (the same as the default IPv4). Both settings work for me. You might try running a portable instance of HTTP Downloader (so that all the settings are default), enabled the server in the Connection options and see if you can get it download. Make sure there aren't any other instances of HTTP Downloader running.

Anyway, I'm glad you're able to get the EPUB files.
