### ISSUE TITLE
Keyboard not working in Add URL Box

### ISSUE THREAD

**Issue by t214c** [erickutcher/httpdownloader#65]
v 1.0.2.3

Some key do not work when adding links.

At least:
arrows
delete
home
end

**Comment by erickutcher** [comment]
Ha! I'll have a fix for this in the next release. I had modified the behavior of the edit control a bit so that you can press Ctrl + Shift + Enter to add the downloads. I guess stopped some of the other keys from working.

**Comment by erickutcher** [comment]
New version is up that fixes this.
