### ISSUE TITLE
Chrome, Firefox extensions for Video (and etc.) download

### ISSUE THREAD

**Issue by truefriend-cz** [erickutcher/httpdownloader#66]
Author, Do you plane create extension for Chrome and Firefox for Video downloading?
Or do you know solution how i can now?

Idea by Internet Download Manager and Xtreme Download Manager

**Comment by erickutcher** [comment]
Any audio or video media that's a single file (mp3, avi, mkv, mp4, etc.) can be downloaded with the current extensions. Video that comes from Youtube and similar sites don't use a single file. They break them up into chunks and it has to be recreated. All of that is outside the HTTP protocol and so you'll have to use other programs for that. I wouldn't be able to recommend anything unfortunately.

**Comment by truefriend-cz** [comment]
Ok. I tested your HTTP Downloader Chrome Extension. And it is good. Have saving from context menu. But any videos can not show context menu or menu olny "About player", etc. Or no "Browser menu".
Do you can add to your Extension detect play MP4 (etc.) on page?
As extension Video Downloader, etc. after left click mouse button on extension icon in browser show actually detected mp4 videos on webpage.
Now after click on icon by left mouse button show settings tab, but... i can show Setting tab from way... right click mouse and select Settings.

**Comment by erickutcher** [comment]
Is there any particular site that I'd be able to test this on?

If you right click on the page instead of the video, then any downloadable videos that are on the page will bring up a "Download All Media..." menu item in the HTTP Downloader context menu.

**Comment by truefriend-cz** [comment]
Yes.
[Tallest Pencil Tower](https://www.myvidster.com/video/4411567/Tallest_Pencil_Tower_-_Danie_Desrosiers)

**Comment by erickutcher** [comment]
I see what's going on. They have a <video> element on the page and are using its "src" attribute. My extensions look for the <source> element instead. Shouldn't be too difficult to fix.

**Comment by erickutcher** [comment]
I've updated the extensions to correct various embedded media (audio, video) not being retrieved.
