### ISSUE TITLE
Basic FTP Support

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#68]
I do not need another FTP client- I have several free ones and they completely satisfy my needs. I would just suggest that **HTTP Downloader** can download FTP links (`ftp://ftp`). Some time ago I  tried to download some files (from [here](https://www.altap.cz/salamander/downloads/)), the download links were hidden and for a while I was thinking that the browser integration was somehow broken as the downloads were handled by the browser, not by **HTTP Downloader** so I was enabling/disabling the browser integration, re-installing the extension until I finally got that the files I was trying to download were FTP links:

- ftp://ftp.altap.cz/pub/altap/salamand/as40x86.exe
- ftp://ftp.altap.cz/pub/altap/salamand/as40x64.exe

So for me it would be convenient if **HTTP Downloader** could handle such links. I am aware that the name of the program implies only HTTP downloads but basic FTP support for just getting FTP links would be handy as such downloads would not be passed to the browser.

I suppose that support for FTP links would not require too much work. Anyway, if this suggestion is rejected I would not be disappointed.

**Comment by erickutcher** [comment]
The protocol seems simple enough. It would just take time to implement and integrate it properly. I still want to implement what I stickied first though. I'll add it to my todo list, but I'm not sure when I'll get to it.

**Comment by smaragdus** [comment]
@erickutcher 

> I'll add it to my todo list, but I'm not sure when I'll get to it.

Thank you, take your time, I am not in a hurry. I prefer such FTP links to e handled by a download manager than the browser because for example **HTTP Downloader**  can get time and date from server.

**Comment by erickutcher** [comment]
So I got this working. It can even break up a download into parts. I'm not going to implement FTPS or SFTP though. It's too hot to think about encryption right now.

**Comment by smaragdus** [comment]
@erickutcher 

> So I got this working. It can even break up a download into parts.

Good news, thanks.

> I'm not going to implement FTPS or SFTP though. It's too hot to think about encryption right now.

Perhaps in the future when it is colder? ;)

**Comment by blackcrack** [comment]
he lives in europe (like me), there was a heatwave , and was ~37 - 40 C° around.. warm enough to say, we make a heat break :) :+1: 
here in germany near stuttgard rains already :) so, can you have a hope *bg*

best regards
Blacky

**Comment by erickutcher** [comment]
I'm actually in Southern California ;-)

**Comment by erickutcher** [comment]
Here's a beta you can test out: [HTTP_Downloader_1.0.2.7_Beta_1.zip](https://github.com/erickutcher/httpdownloader/files/3465707/HTTP_Downloader_1.0.2.7_Beta_1.zip)

The zip file includes a 32-bit and 64-bit version. They both have a "portable" file as well so that it doesn't interfere with any normal release you have on your system. Try not to distribute this as it is a beta.

It supports FTP and FTPS (both explicit and implicit).

Here's some example links you can try. The username for them is "demo" and the password is "password".

- Regular FTP: `ftp://test.rebex.net/readme.txt`
- Explicit FTPS: `ftpes://test.rebex.net/readme.txt`
- Implicit FTPS: `ftps://test.rebex.net/readme.txt`

I've also added support for username and password values inside the URL. This works for both HTTP(S) URLs and FTP/FTPS/FTPES URLs.

Here's an example of that:

- HTTP(S) auth: `http://user1:user1@test.webdav.org/auth-basic/`
- Regular FTP: `ftp://demo:password@test.rebex.net/readme.txt`
- Explicit FTPS: `ftpes://demo:password@test.rebex.net/readme.txt`
- Implicit FTPS: `ftps://demo:password@test.rebex.net/readme.txt`

**Comment by smaragdus** [comment]
@erickutcher 

Thank you very much. I downloaded the archive and I will test it tonight. Thanks for the FTP links too. I have a very simple FTP server installed so I will test it with links that require user name and password.

**Comment by smaragdus** [comment]
@erickutcher 

I did a brief test of **HTTP Downloader** version **1.0.2.7 Beta 1**, test results:

I did manage to get all the links you provided with the exception of the WebDAV link- I got **auth-basic** file with the following content:

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /auth-basic/ was not found on this server.</p>
<hr>
<address>Apache Server at test.webdav.org Port 80</address>
</body></html>
```
Is this what I was supposed to get?

I could not grab the links I provided in my first post:

- ftp://ftp.altap.cz/pub/altap/salamand/as40x86.exe
- ftp://ftp.altap.cz/pub/altap/salamand/as40x64.exe

These downloads timed out.

I could not download files from my FTP server- first I opened a FTP client, copied a link without log-in information and input the log-in information manually- the download stopped. Then I copied a link with with log-in information and again I could not download the file- the download stopped. The links I was using were like these:

- ftp://address:21/C/FTP/Archives/file-name.7z
- ftp://user:password@address:21/C/FTP/Archives/file-name.7z

**Screen**

![HTTP Downloader 1 0 2 7 Beta 1 - 2019-08-06 - 002](https://user-images.githubusercontent.com/9025757/62503078-42637780-b7fb-11e9-8720-3f2d3a5d6c02.png)

I do not know what caused the problem. Does **HTTP Downloader** understands FTP active/passive modes? Does **HTTP Downloader** handle any ports information? I suppose that these downloads failed because the links contained port addresses. If needed I can create an account for you at my FTP server (it is on most of the time).

**Comment by erickutcher** [comment]
The WebDAV response is correct.

As far as the Altap server goes, it seems flaky to me. Sometimes it works, sometimes it doesn't. I'm wondering if they're rate limiting on their end? Restart it a couple of times and it should work.

HTTP Downloader only uses extended passive mode (EPSV). If the server is behind a firewall and can't open up a port for the data connection, then it's not going to be able to download it. Public FTPs don't usually have that problem. I'll look into having an extended active mode (EPRT) option as well.

The port addresses in the URLs are fine.

**Comment by erickutcher** [comment]
The command requests for the Altap server might be going too fast. I've noticed that if I add a delay before sending the request, then it works without issue. It needs a closer look.

**Comment by erickutcher** [comment]
Here's a second beta to test out: [HTTP_Downloader_1.0.2.7_Beta_2.zip](https://github.com/erickutcher/httpdownloader/files/3532751/HTTP_Downloader_1.0.2.7_Beta_2.zip)

It should be much more versatile in handling FTP commands/replies. There's a new FTP tab in the Options window. You can set Passive or Active mode and various other things. For Active mode, you'll want to supply your WAN IP and open up the necessary ports. Some routers will let you use your local IP without the need to open up ports, but it'll only work with unencrypted FTP connections. If you don't _need_ to use Active mode, don't use it.

The program will default to using EPSV/EPRT for Passive/Active modes and fall back to PASV/PORT for older servers.

I'm interested in servers that don't work with HTTP Downloader, but will in other clients.

**Comment by smaragdus** [comment]
@erickutcher 

Thanks for the new Beta. I downloaded and I will have a look either tonight (here it is 7 AM now) or tomorrow. I will try it with my primitive FTP server too.

**Comment by smaragdus** [comment]
@erickutcher 

I finally updated to HTTP Downloader version 1.0.2.8 and extensions to version 1.0.1.1 and did some initial tests. When I add FTP download links manually all files are downloaded right. When I copy download links from my FTP client of files on my FTP server (links with user name/password)- all files were downloaded fine too (with the right time stamp). But when I click FTP links in browsers (both Chromium-based and Firefox-based) the downloads are not intercepted by HTTP Downloader but are downloaded by the browsers. Am I missing something?

**Comment by erickutcher** [comment]
The extensions weren't checking for FTP URLs. I fixed it.

**Comment by smaragdus** [comment]
@erickutcher 

> The extensions weren't checking for FTP URLs. I fixed it.

Thank you!

**Comment by smaragdus** [comment]
@erickutcher

I tested HTTP Downloader version 1.0.2.9 with Chromium extension version 1.0.1.3. HTTP Downloader was able to download all the FTP files I tested it with (intercepting FTP links from the browser), including [Altap Salamander](https://www.altap.cz/salamander/downloads/). However the first time I tried to download from Altap Salamander website I got the following error:

![HTTP Downloader 1 0 2 9 - 2019-11-25 - error - 001](https://user-images.githubusercontent.com/9025757/69575247-8361e080-0fd2-11ea-9618-642e2e7ac30a.png)

I suppose that the problem was with the server. So I think that this issue can be closed as FTP downloads work fine in almost all cases (including FTP downloads with credentials). The FTP support you implemented exceeds my expectations, really excellent work, thank you very much!

What I didn't like that much was the fact in version 1.0.2.9 that I had to set up my settings again and download history from previous version was lost but I suppose that this was inevitable.

I would like to ask- is HTTP Downloader History Editor able to export download history from previous versions of HTTP Downloader to download history format used in version 1.0.2.9?

**Comment by erickutcher** [comment]
I changed the format of the settings and history files in 1.0.2.9. So as you said, it was inevitable.

The History Editor can import older download history files and, when saved (or overwritten) by the editor, will update them to the latest version.

**Comment by smaragdus** [comment]
@erickutcher 

> The History Editor can import older download history files and, when saved (or overwritten) by the editor, will update them to the latest version.

This was all I needed to know, thanks for the confirmation.

**Comment by erickutcher** [comment]
I've been able to implement SFTP support (secure shell file transfers). I modified the source code for psftp, which is part of PuTTY's suite of software, and turned it into a DLL. My program handles the connection stuff and I just pass psftp all of the raw data to encrypt and decrypt. It'll take some time to clean things up. The PuTTY code is nuts.

**Comment by erickutcher** [comment]
The new version has SFTP support now. It's an optional DLL called psftp.dll.
