### ISSUE TITLE
Small memory leak when downloading a file

### ISSUE THREAD

**Issue by Zero3K** [erickutcher/httpdownloader#78]
Program Version: 1.0.2.6 (32-bit)

When I downloaded a 6 GB file (the one at https://az792536.vo.msecnd.net/vms/VMBuild_20190311/VirtualBox/MSEdge/MSEdge.Win10.VirtualBox.zip), the memory usage goes from 4-5 MB to 13-15 MB. Please look into seeing if its something that can be fixed or not.

**Comment by erickutcher** [comment]
You'll have to tell me the program version as well as whether it's 32-bit or 64-bit.

I did a simulated download for that URL with 100 connections (which is overkill) and it went from 7 MB to 14 MB. That seems normal to me. Each connection is going to use some bit of memory and it'll linger around for a while. All of the memory that's allocated for each connection is cleaned up when it gets closed. I can almost guarantee you that there's no memory leak.

**Comment by Zero3K** [comment]
I didn't notice the memory usage decreasing after the download was done.

**Comment by erickutcher** [comment]
Windows retains memory for a while. Also, there's probably memory being consumed by delay loaded DLLs. Try redownloading the file a few times (keeping the program open the entire time) and you'll see the memory will remain consistent.
