### ISSUE TITLE
Tool Bar

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#8]
You may consider adding a tool bar for quick access to most common commands ('Add', 'Start', 'Pause', 'Stop', 'Options', 'Exit', etc) which are currently accessible from menu bar and from context menu. Tool bar may be disabled by default, accessible from 'View' menu. I think that using tool bar commands would be faster than using the current commands- for example- using tool bar button 'Add URL(s)' will require 1 click, using 'Add URL(s)' command from menu bar requires 2 clicks, the same for example for 'Pause'- 1 click if executed from 'Pause' tool bar button, 2 clicks if executed from context menu (right-click on a download, then 'Pause').

By the way what is the difference between 'Pause' and 'Stop' commands?

**Comment by erickutcher** [comment]
This is easy enough. My biggest problem with it is creating icons. I'm never satisfied with how they look. I'll see what I can do.

**Comment by erickutcher** [comment]
I forgot to mention about the Pause and Stop commands. Pause will keep the connection active, but it won't download any data. Stop will close the connection and clean up any memory associated with it. A paused download may end up getting closed if the server it's connected to times out the connection for inactivity.

**Comment by smaragdus** [comment]
Thanks for clarifying the difference between 'Pause' and 'Stop'.

About tool bar icons- you may choose to use free icons in stead of creating your own icons.

There are free icon collections, examples:

- [Silk Icons](http://www.famfamfam.com/lab/icons/silk/)
- [Fugue Icons](http://p.yusukekamiyamane.com/)
- [Xiao Icon](https://www.deviantart.com/delacro/art/Xiao-Icon-84772282)

I suppose that more free icon sets can be found.

**Comment by erickutcher** [comment]
I ended up making my own bitmap icons to keep the file size down. Just couldn't find any free stuff that I liked.

The toolbar has add, remove, start/resume, pause, stop, pause active, stop all, and options.

**Comment by smaragdus** [comment]
Excellent tool bar buttons, simple and nice-looking, good job!
The tool bar looks sharp and cute and I am glad you added it. Thank you so much!
