### ISSUE TITLE
Sorting isn't being automatically applied

### ISSUE THREAD

**Issue by Zero3K** [erickutcher/httpdownloader#80]
Program Version: 1.0.2.6 (32-bit)

I had it set to sort by "Date and Time Added" in descending order (from newest to oldest) and the new downloads were placed at the bottom when they should've been at the top.

**Comment by erickutcher** [comment]
Sorting is an inefficient process so new URLs get added at the end. You'll have to manually sort to keep new downloads at the top. I'll see what kind of solutions there are to make it retain the sort and still be fast (when adding URLs).

**Comment by erickutcher** [comment]
Haven't looked into it. Been busy with SFTP connections.

**Comment by Zero3K** [comment]
Okay. That's nice that it'll support those soon :smiley:

**Comment by erickutcher** [comment]
Not soon. The SSH protocol is nuts.

**Comment by Zero3K** [comment]
I guess you found a way to fix it?

**Comment by erickutcher** [comment]
Remembering the sorted column and sort order wasn't a problem. It's keeping things sorted when adding or while items are updating that poses the problem. It's just not efficient. I made sorting while items are added or updating an option in the Appearance options.

The sort can be removed by clicking on the # column button.

**Comment by Zero3K** [comment]
Why is it an option? Is there no way to have it happen like in Internet Download Manager, etc.?

**Comment by erickutcher** [comment]
When an item is added to the list and then sorted into the correct position, the entire list has to be accessed and each item's values have to be compared. Now imagine it sorting every second while a downloading is going. It's not efficient. That's why I made it an option. I also have no control over the listview's sorting algorithm. If I did, I could do some tricks to make it efficient, but it is what it is.

If I ever get around to finishing my treelistview control, then sorting efficiency won't be an issue.

**Comment by Zero3K** [comment]
Maybe you could offer the source code that you have of the treelistview control on https://gist.github.com and link to it here so people can help with finishing it.

**Comment by Zero3K** [comment]
The option that you added regarding this issue doesn't work for me.

**Comment by erickutcher** [comment]
Make sure that you have a column sorted first.  So, for example, if you want new downloads to appear at the top, then make sure the "Date and Time Added" column is sorted in descending mode (arrow going down) and that the option in the Options window has been set.

**Comment by Zero3K** [comment]
I did that and its still not working.

**Comment by erickutcher** [comment]
I'm not able to confirm this. Are you able to record a video to demo it for me?

**Comment by Zero3K** [comment]
Its still happening in the latest version. I have a down arrow next to "Date and Time Added" and clicked the checkbox in its Options that is supposed to enable the automatic sorting.

**Comment by erickutcher** [comment]
I'm not sure what's going on. I can get it to work fine in Windows XP, 7, and 10. Maybe try it on another system?

**Comment by Zero3K** [comment]
It still happens even when I deleted all of the entries in the Download History.

**Comment by Zero3K** [comment]
This is still happening.

**Comment by erickutcher** [comment]
You'll have to record a video. Show the settings in the Options window and then show how the download window behaves when you add URL(s). Make sure the column you want sorted is visible in the video too.

**Comment by Zero3K** [comment]
It works now. So, I am closing this issue.
