### ISSUE TITLE
Issue with downloading a certain URL

### ISSUE THREAD

**Issue by Zero3K** [erickutcher/httpdownloader#81]
Program Version: 1.0.2.6 (32-bit)

When I download http://-----------.7z , it'll stop downloading after a while.

**Comment by erickutcher** [comment]
That particular link can only use one connection. If you've set it to download with more than one part, then when it finishes with the first part it'll attempt to restart and download the next part. Depending on how many incomplete download retries you have set in the Options, then it'll eventually stop after a certain amount of retries. Right click on the file and select "Update Download...". Set the download parts to 1 and then resume it.
