### ISSUE TITLE
Issue with downloading a certain URL (#2)

### ISSUE THREAD

**Issue by Zero3K** [erickutcher/httpdownloader#84]
It cannot download https://www.hiawatha-webserver.org/files/hiawatha-9/hiawatha-9.15.zip. It just goes to Stopped status with a size of "? B".

**Comment by erickutcher** [comment]
This is a Windows issue. Specifically with Schannel. That site will work on Windows 10 (probably 8 and 8.1 too), but it won't work on Windows 7 or earlier.

You can test this out by trying to access it with Internet Explorer (which uses Schannel).

I won't be able to fix this without using a different API, like OpenSSL, and I don't want to do that.

I haven't updated my copy of Windows 7 in a million years so maybe the latest updated version works?

**Comment by Zero3K** [comment]
I am able to download it on Windows 7 SP1 x64 using the latest version of Pale Moon.

**Comment by Zero3K** [comment]
It seems that whatever the site uses is disabled by default in Windows 7's implementation of SChannel.

**Comment by erickutcher** [comment]
I got it working, but I'm not sure what the true solution is.

I'm going to give you a debug version and you can tell me if it works. If it doesn't, then I'll send you some Microsoft update links that might have fixed things for me.

**Comment by erickutcher** [comment]
Here's a new version you can try: [HTTP_Downloader_1.0.2.7_Beta_3.zip](https://github.com/erickutcher/httpdownloader/files/3537853/HTTP_Downloader_1.0.2.7_Beta_3.zip)

For that particular site you will want to set the SSL / TLS version to TLS 1.1. You can change this in the Update Download window or set it in the Advanced options in the Add URL(s) window.

Let me know if that works for you.

**Comment by Zero3K** [comment]
It doesn't work. Also, I got a message stating that the zlib couldn't be loaded even though its in the directory where HTTP Downloader is located.

**Comment by Zero3K** [comment]
I guess the only way to support it is to use a different SSL library.

**Comment by erickutcher** [comment]
Read this and follow its instructions: https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi

You will want to install this update: http://catalog.update.microsoft.com/v7/site/search.aspx?q=kb3140245

And apply the Easy fix: https://support.microsoft.com/en-us/help/3140245/update-to-enable-tls-1-1-and-tls-1-2-as-default-secure-protocols-in-wi#easy

I don't know if that update and fix really did anything for me, but it won't hurt to try.

The URL does work, you just need to have the right setup.

![tls11](https://user-images.githubusercontent.com/7762164/63652662-815c5d00-c717-11e9-8448-83b22ef6a532.png)

**Comment by Zero3K** [comment]
1. The update was already applied since I got it a while back.
2. Running the Easy Fix that you linked to got it to work. So, you could add an option to have it apply the registry settings that the KB article mentions or have it done automatically when its first ran.

**Comment by erickutcher** [comment]
I don't touch the registry. Since it's one site that causes issues, it's not worth doing a workaround. That's what all the options are for. Try one until it works.

As far as the zlib issue goes. Did you extract all of the files in the zip or did you run it from the zip? Everything needs to be extracted for it to work.

**Comment by Zero3K** [comment]
1. Maybe its more than one site. You could include the .reg so people can fix it if they run into it.
2. Yes I did. I am using the 32-bit version on a 64-bit OS though.

**Comment by erickutcher** [comment]
It's a Windows issue. I don't want to have the program do anything to the system. I leave that to the user. As long as the system is up to date, or running the latest version of Windows, then it shouldn't be a concern.

**Comment by Zero3K** [comment]
Maybe you can mention it in the Readme.

**Comment by Zero3K** [comment]
Is that a good idea or not?

**Comment by erickutcher** [comment]
I don't really think it's a critical issue. If I get a lot of reports about it, then maybe I'll mention something.

**Comment by Zero3K** [comment]
Okay. I'll close this issue for now.
