### ISSUE TITLE
Automatically set the SSL/TLS Version

### ISSUE THREAD

**Issue by Zero3K** [erickutcher/httpdownloader#85]
It would be nice if that was done so the user doesn't have to manually change it for certain URLs.

**Comment by erickutcher** [comment]
Not necessary. The client sends multiple versions that it can handle and the server and client agree to use what's offered. That one server was too strict and Windows 7 is too old. It should work for 99.99% of the sites out there.

**Comment by Zero3K** [comment]
Thanks for explaining.
