### ISSUE TITLE
32-bit version of Zlib not being found

### ISSUE THREAD

**Issue by Zero3K** [erickutcher/httpdownloader#87]
Program Version: 1.0.2.7 Beta 3
OS: Windows 7 SP1 (64-bit)

The 32-bit version of Zlib isn't being found (which is causing the dialog box to pop-up) even though it is in the directory where HTTP_Downloader.exe is located.

**Comment by erickutcher** [comment]
The 32-bit version of the zlib.dll file is 122 KB in size. The 64-bit one is 109 KB. Are you sure it's paired with the correct version of the program?

**Comment by Zero3K** [comment]
It was 0 bytes for some reason.
