### ISSUE TITLE
Suggestion regarding downloaded archives

### ISSUE THREAD

**Issue by Zero3K** [erickutcher/httpdownloader#88]
Program Version: 1.0.2.7 Beta 3
OS: Windows 7 (64-bit)

It would be nice if it could automatically extract multi-part/single-part archives to the folder they are downloaded to after all parts have finished downloading.

**Comment by erickutcher** [comment]
If I do anything related to archives, it would be to call an external program on the completed download. Personally, I use a download manager to download and an archive manager to deal with archives.

**Comment by Zero3K** [comment]
That makes sense.
