### ISSUE TITLE
Browser Integration

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#9]
This is more a question than a request. I managed to add the **Chrome Extension** (version **1.0.0.1**) of **HTTP Downloader** to two Chromium-based browsers ([Cent Browser](https://www.centbrowser.com/) and [Vivaldi](https://vivaldi.com/)):

![http_downloader_chrome_extension 1 0 0 1 - 2018-09-30 - 002](https://user-images.githubusercontent.com/9025757/46260907-0a154d80-c4f5-11e8-80e4-f0eafc77575b.png)

it had options menu:

![http_downloader_chrome_extension 1 0 0 1 - 2018-09-30 - 004](https://user-images.githubusercontent.com/9025757/46260921-2a450c80-c4f5-11e8-96be-2efb3c3b6472.png)

and it appeared on extensions bar:

![http_downloader_chrome_extension 1 0 0 1 - 2018-09-30 - 006](https://user-images.githubusercontent.com/9025757/46260926-37fa9200-c4f5-11e8-962a-b93e0a51a1f2.png)

but it did nothing, My expectation was that new downloads should be passed from the browser to **HTTP Downloader** (via 'Add URL(s)' dialog) but nothing like that happened. Am I missing something? How is **Chrome Extension** supposed to work?

I also tried to integrate **HTTP Downloader** with an old, pre-Quantum version of **Firefox** via [FlashGot](https://flashgot.net/):

![http downloader 1 0 0 7 - 2018-09-30 - flashgot - 001](https://user-images.githubusercontent.com/9025757/46261045-e226e980-c4f6-11e8-9079-bdbe586a9d82.png)

but I failed again because I did not know what placeholder should I use. Is  it possible to integrate **HTTP Downloader** with **Firefox** (versions **57** and older) via **FlashGot** add-on?

**Comment by erickutcher** [comment]
Setting up browser support is a bit involved. I should probably document it a little better.

You'll need to go into the program's options and select "Enable server" under the Connection tab. The values should match the values in the browser extension's options.

Then go on any webpage and right click a link you want to download. You should see a menu called "HTTP Downloader" that'll give you various download options. When you click on one of those menu items it'll pop up a window that looks like the Add URL(s) window from the program. Click the Download button and it'll send the link and any of its necessary information (header values, cookies, etc.) to the program to download.

With regard to FlashGot. HTTP Downloader doesn't have any command-line switches to load URLs so sending it anything with FlashGot isn't going to work. I'll look into implementing something.

**Comment by smaragdus** [comment]
I posted a short [tutorial](https://www.portablefreeware.com/forums/viewtopic.php?f=4&t=24325&p=91777#p91777) with screen-shots about **HTTP Downloader** integration with Chromium-based browsers.

**Comment by erickutcher** [comment]
I'm glad to see you got it working. It's a handy feature if you ever wanted to download an open directory and filter out certain file types.

As far as stealing/intercepting download links go, I'd rather there be a proper API that can alert the extension before a link goes to the browser's download manager (so it can be redirected to another download manager). Any other way just isn't clean.

**Comment by erickutcher** [comment]
I suppose I can create a .crx file for the next release.

There's no reason why I have different icons. I just tried to make something that looked nice for the browser and never bothered to update the program's icon. I hate making icons.

I'll have to look more into the browser download APIs and see what can be done that works nicely.

**Comment by erickutcher** [comment]
I replaced the .zip with a .crx file.

**Comment by smaragdus** [comment]
@erickutcher 

> I replaced the .zip with a .crx file.

Thank you.

**Comment by erickutcher** [comment]
The latest versions should allow you to download those weird POST downloads. You can also override the browser's download manager. If you do override it, you can also have it bring up the Add URL(s) window before the file starts downloading.

The extension will ignore whatever you name a file if you save it with any of the "Save As..." menus. It will, however, use the folder you want to save the file to. Maybe I'll add support for the filename at a later time.

I also fixed some cookie related issues. The cookie strings weren't being formatted properly when they were sent to the program. They also weren't showing up in Incognito mode for Chrome/Chromium based browsers. All that's hopefully fixed now.

**Comment by smaragdus** [comment]
@erickutcher 

I came upon a site ([VENEA.NET](https://www.venea.net/)) from which **HTTP Downloader** version **1.0.1.0** cannot download files- go to [Downloads](https://www.venea.net/web/downloads) and try to download **NetTraffic** or **NetTraffic Portable**, I failed using **Chrome Extension** version **1.0.0.2**. Please confirm the problem.

**Comment by erickutcher** [comment]
There's definitely strange behavior with that site. I did get it to download, but it's flaky. One of the reasons why it's not working is because it requires the Referer header to be passed in the request which the extensions don't do by default. I may change that behavior and have them send the Referer and User-Agent values.

That particular site wants a Cookie and the Referer to be passed. For whatever reason the initial download fails, but restarting it works. It's like their server wants two connections to be made before serving the file. That's probably why there's a delay on the page. And also to force the advertisements to load. The browsers work because they've already made other connections at that point.

I don't think I want to cater a fix for that since it seems dependent on interacting with the server in a nonstandard way. The workaround, when I release the new version and update the extensions, will be to restart the download after it completes the first time. That seems to work for me.

**Comment by erickutcher** [comment]
The new version is up along with the extensions. And with the fix for restarting completed downloads, the workaround for this site should let it download.

The first time you download one of their files it won't get the actual file, but if you restart it after it completes, then it'll get the correct one. That's what I've observed with my testing. For them to serve two different files with the exact same request data, means that the download is dependent on interaction with the site. For a web browser that's not a problem, but download managers aren't expected to know that. So that's why most, if not all, will fail.

**Comment by smaragdus** [comment]
@erickutcher 

I updated both HTTP Downloader to version 1.0.1.1 and Chrome Extension to version 1.0.0.3. I tested it again with the above mentioned site, followed your procedure and it worked as you explained. The only tiny inconvenience is that the restarted downloads leave the empty downloads ('nettraffic' for 'NetTraffic 1.53.0.zip' and 'nettraffic_portable' for 'NetTraffic Portable 1.53.0.zip') on disk and they have to be deleted manually but if course this is not a real problem. Thank you for the workaround, it is effective!

**Comment by smaragdus** [comment]
The download workaround for this evil site (venea.net) no longer works- restarting the download does not result in completing the download. Perhaps the developer is reading this thread and is taking counter-measures. ;)

**Comment by smaragdus** [comment]
I failed to download this [file](https://fastcopy.jp/archive/FastCopy360_installer.exe) from this [site](https://fastcopy.jp/en/)- the download via browser and via another downloads manager were successful.

**Comment by smaragdus** [comment]
> Seems to still work for me. Perhaps you'll need to restart it within some amount of time. Because it uses a cookie, their server might set an expiration on it. Make sure that "Send Referer header" is set in the extension's options.

This time I managed to download the files.

**Comment by erickutcher** [comment]
> 
> 
> I failed to download this [file](https://fastcopy.jp/archive/FastCopy360_installer.exe) from this [site](https://fastcopy.jp/en/)- the download via browser and via another downloads manager were successful.

There wasn't anything special with that particular file or site. I was able to get it to work in Firefox and Chrome and by copying the link directly into the program. Did it download something else, or not at all?

**Comment by smaragdus** [comment]
I first tried to download a 404 file- the [source code](https://fastcopy.jp/archive/FastCopy360src.zip), which was normal to fail. Then the available file also failed. But now I restarted HTTP Downloader and the download was successful. I think that HTTP Downloader downloaded a web page and I could delete it only when I exited the program. Perhaps this was my fault. Please excuse me for wasting your time!

**Comment by smaragdus** [comment]
I would like to inform you that downloads from [VENEA.NET](https://www.venea.net/web/downloads) still fail (restart does not help).

**Comment by erickutcher** [comment]
Yes, I received an email from another user with regard to that particular site. The conclusion that I reached was that it was something they're doing with cookies. Can't really say for sure. If you restart the download by right clicking on it and selecting Restart, then it'll work. Strange behavior, but I don't think I can fix it.
