### ISSUE TITLE
Downloading GitHub Avatars

### ISSUE THREAD

**Issue by smaragdus** [erickutcher/httpdownloader#99]
When I try to download an avatar of GitHub user (for example- [user](https://github.com/zhanghai), [image](https://avatars1.githubusercontent.com/u/4469895?s=400&v=4)) using 'Save as...' browser dialog the browser shows the file right (in this case- '4469895.png' but HTTP Downloader (version1.0.2.9 x64) does not append file extension (in this case- PNG) so in stead of downloading the file as '4469895.png' it saves it as '4469895' (without extension). So I have either to rename the file from inside HTTP Downloader (using 'Rename' context menu command) or rename it in a file manager. Can you confirm this problem? It is a minor issue yet it would be nicer if HTTP Downloader could append the right extension when downloading such image files from GitHub.

**Comment by erickutcher** [comment]
The browser is using the Content-Type header to determine the file extension when there is none. In this case it sees "image/png" and appends the appropriate extension.

I'll see about supporting common file types.

**Comment by erickutcher** [comment]
Here's a beta version that implements Content-Type detection. It should rename extensionless files based on the header value. https://github.com/erickutcher/httpdownloader/files/4028784/HTTP_Downloader_64_1.0.3.0_Beta_3.zip

It detects: html, js, css, json, txt, jpg, gif, png, mp3, mpeg, zip, gz, svg, pdf, xml, xhtml

I also implemented the ability to manually rename links in the Add URL(s) window. You can do this by adding [_filename_] before the link.

The following example will force the naming of image.jpg to test.jpg:

`[test.jpg]http://www.example.com/image.jpg`

The updated browser extensions will have the ability to automatically fill in the brackets if the user uses the browser's Save As... dialogs.

**Comment by smaragdus** [comment]
@erickutcher 

> Here's a beta version that implements Content-Type detection. It should rename extensionless files based on the header value.

I tested HTTP Downloader  version 1.0.3.0 Beta 3 (64-bit) but downloading GitHub avatars I got again files without extensions, I was adding the download links manually. Perhaps I am mission something?

I think I noticed something else- it seems that the task bar icon has been changed, screen:

![HTTP Downloader - 2020-01-08 - task bar icon - 005](https://user-images.githubusercontent.com/9025757/72019176-d84f7280-3271-11ea-97a4-a9e0ed9cc63d.png)

Is that true? For me the task bar icon in version 1.0.2.9 looks slimmer and prettier while the task bar icon in version 1.0.3.0 looks thicker and uglier.

**Comment by erickutcher** [comment]
I fixed the GitHub links not being detected. It was only detecting the content type for links that had no filename. (like `http://www.example.com/`)

As for the icon, I'm not sure why it looks like that. It hasn't been changed. Try running Disk Cleanup on your system and make sure that Thumbnails gets cleaned up. I'm wondering if maybe Windows cached a weird icons for some reason.

**Comment by smaragdus** [comment]
@erickutcher 

Thanks for the quick response.

> I fixed the GitHub links not being detected. It was only detecting the content type for links that had no filename. (like `http://www.example.com/`)

Excellent!

> As for the icon, I'm not sure why it looks like that. It hasn't been changed. Try running Disk Cleanup on your system and make sure that Thumbnails gets cleaned up. I'm wondering if maybe Windows cached a weird icons for some reason.

You are right, I didn't think of that. Currently I am doing some cleaning using different tools. If the problem persists I will try restart- restarting often cures such problems.

**Comment by smaragdus** [comment]
@erickutcher 

After restart the problem with the thicker task bar icon seems to be resolved. Yet I do not know how and why it happened.

**Comment by erickutcher** [comment]
The latest version is up.

**Comment by smaragdus** [comment]
@erickutcher 

Getting GitHub avatars via HTTP Downloader results in files with extensions, everything works as expected, thanks! Version [1.0.3.0](https://github.com/erickutcher/httpdownloader/releases/tag/v1.0.3.0) seems to be a massive update and improvement, excellent work!
